import type { SoilEntity } from "./types";

export const SOIL_ENTITIES: SoilEntity[] = [
  {
    slug: "soap-scum",
    name: "Soap Scum",
    kind: "soil",
    summary:
      "A stubborn bathroom residue formed when soap fats react with hard water minerals and dry onto surfaces.",
    aliases: ["soap residue", "bath soap buildup"],
    relatedArticleSlugs: [
      "how-to-clean-shower",
      "how-to-remove-soap-scum",
      "bathroom-cleaning-guide",
      "how-to-clean-glass-shower-door",
    ],
    relatedServiceSlugs: ["bathroom-cleaning", "deep-cleaning"],
    category: "mineral-fatty residue",
    composition: [
      "soap fatty acids",
      "hard water minerals",
      "body oil residue",
      "trapped moisture film",
    ],
    formsFrom: [
      "soap use in hard water environments",
      "repeated wet-dry bathroom cycles",
      "insufficient rinsing and drying",
    ],
    commonLocations: ["showers", "tubs", "glass shower doors", "tile walls", "fixtures"],
    affectedSurfaceSlugs: ["glass", "ceramic-tile", "porcelain-tile", "fiberglass", "chrome"],
    recommendedMethodSlugs: ["acid-cleaners", "mechanical-agitation", "microfiber-cleaning"],
    avoidMethodSlugs: ["abrasive-scraping"],
    recommendedToolSlugs: ["microfiber-towel", "non-scratch-scrub-pad", "grout-brush", "squeegee"],
    avoidToolSlugs: ["steel-wool", "metal-scraper"],
    visualSignals: [
      "cloudy white film",
      "chalky residue",
      "dull patching on glass",
      "layered buildup around water lines",
    ],
    safetyNotes: [
      "Confirm the surface is acid-compatible before using acidic chemistry.",
      "Do not confuse etching with removable buildup.",
    ],
    professionalEscalationThresholds: [
      "buildup is layered and long-standing",
      "glass may be etched rather than dirty",
      "surface finish damage is possible",
    ],
    riskLevel: "low-medium",
  },
  {
    slug: "hard-water-stains",
    name: "Hard Water Stains",
    kind: "soil",
    summary:
      "Mineral deposits left behind as water evaporates, often appearing as white haze, crust, or spotting.",
    aliases: ["mineral deposits", "limescale", "water spotting"],
    relatedArticleSlugs: [
      "how-to-remove-hard-water-stains",
      "how-to-clean-shower",
      "how-to-clean-windows",
    ],
    relatedServiceSlugs: ["bathroom-cleaning", "window-cleaning", "deep-cleaning"],
    category: "mineral deposit",
    composition: ["calcium", "magnesium", "silicate residue", "evaporation deposits"],
    formsFrom: [
      "repeated evaporation of mineral-rich water",
      "poor drying after rinsing",
      "high-mineral municipal water exposure",
    ],
    commonLocations: ["faucets", "glass", "showers", "tile", "sink surrounds"],
    affectedSurfaceSlugs: ["glass", "chrome", "stainless-steel", "ceramic-tile", "porcelain-tile"],
    recommendedMethodSlugs: ["acid-cleaners", "microfiber-cleaning"],
    avoidMethodSlugs: ["abrasive-scraping"],
    recommendedToolSlugs: ["microfiber-towel", "non-scratch-scrub-pad", "squeegee"],
    avoidToolSlugs: ["steel-wool", "metal-scraper"],
    visualSignals: ["white spotting", "chalky crust", "opaque haze", "ringing around fixtures"],
    safetyNotes: [
      "Test acidic cleaners before use on sensitive finishes or natural stone.",
      "Do not over-agitate decorative finishes.",
    ],
    professionalEscalationThresholds: [
      "deposits are thick and bonded",
      "surface may be permanently etched",
      "natural stone is involved",
    ],
    riskLevel: "medium",
  },
  {
    slug: "mildew",
    name: "Mildew",
    kind: "soil",
    summary:
      "A surface-level fungal growth encouraged by persistent moisture, poor airflow, and organic residue.",
    aliases: ["surface mildew", "bathroom mildew"],
    relatedArticleSlugs: [
      "how-to-clean-shower",
      "bathroom-cleaning-guide",
      "how-to-clean-grout",
    ],
    relatedServiceSlugs: ["bathroom-cleaning", "deep-cleaning"],
    category: "biological growth",
    composition: ["fungal growth", "moisture-fed organic colonization"],
    formsFrom: [
      "persistent moisture",
      "poor ventilation",
      "organic residue left on wet surfaces",
    ],
    commonLocations: ["grout lines", "caulk lines", "shower corners", "window tracks"],
    affectedSurfaceSlugs: ["ceramic-tile", "porcelain-tile", "grout", "caulk", "painted-drywall"],
    recommendedMethodSlugs: ["oxidizing-cleaners", "mechanical-agitation", "moisture-reduction"],
    avoidMethodSlugs: ["surface-fragrance-coverup"],
    recommendedToolSlugs: ["grout-brush", "microfiber-towel", "detail-brush"],
    avoidToolSlugs: ["shared-dirty-towel"],
    visualSignals: ["dark spotting", "patchy discoloration", "speckling in corners"],
    safetyNotes: [
      "Use ventilation and appropriate PPE where biological growth is present.",
      "Do not assume all dark spotting is superficial mildew.",
    ],
    professionalEscalationThresholds: [
      "growth returns quickly after cleaning",
      "caulk or drywall appears penetrated",
      "there may be moisture intrusion behind the surface",
    ],
    riskLevel: "medium-high",
  },
  {
    slug: "kitchen-grease",
    name: "Kitchen Grease",
    kind: "soil",
    summary:
      "A sticky airborne oily residue that settles on kitchen surfaces and traps dust, soils, and odors.",
    aliases: ["cooking grease buildup", "grease film"],
    relatedArticleSlugs: [
      "how-to-clean-kitchen",
      "how-to-clean-greasy-kitchen-cabinets",
      "kitchen-cleaning-guide",
    ],
    relatedServiceSlugs: ["kitchen-cleaning", "deep-cleaning"],
    category: "oily residue",
    composition: ["cooking oils", "aerosolized fats", "dust-bound residue"],
    formsFrom: [
      "cooking vapors",
      "inadequate ventilation",
      "infrequent degreasing",
    ],
    commonLocations: ["cabinet faces", "range hoods", "backsplashes", "appliance tops"],
    affectedSurfaceSlugs: ["painted-cabinetry", "laminate", "stainless-steel", "ceramic-tile"],
    recommendedMethodSlugs: ["alkaline-cleaners", "microfiber-cleaning", "mechanical-agitation"],
    avoidMethodSlugs: ["overwetting-wood-finishes"],
    recommendedToolSlugs: ["microfiber-towel", "non-scratch-scrub-pad", "detail-brush"],
    avoidToolSlugs: ["steel-wool"],
    visualSignals: ["sticky feel", "yellow-brown film", "dust stuck to surface", "uneven shine"],
    safetyNotes: [
      "Avoid over-wetting wood-based cabinet materials.",
      "Always remove cleaner residue so the surface does not stay tacky.",
    ],
    professionalEscalationThresholds: [
      "heavy grease layering across multiple surfaces",
      "delicate or damaged cabinet finishes",
      "post-construction or neglected buildup conditions",
    ],
    riskLevel: "medium",
  },
  {
    slug: "pet-stains",
    name: "Pet Stains",
    kind: "soil",
    summary:
      "Organic staining and residue from pet accidents that can discolor fibers and hold odor-causing material.",
    aliases: ["pet accident stains", "pet urine stains"],
    relatedArticleSlugs: ["how-to-remove-pet-stains"],
    relatedServiceSlugs: ["deep-cleaning"],
    category: "organic staining",
    composition: ["urine residue", "organic proteins", "pigment residue", "bacteria-supporting matter"],
    formsFrom: ["pet accidents", "incomplete cleanup", "moisture retained in porous materials"],
    commonLocations: ["carpet", "rugs", "upholstery", "baseboard edges"],
    affectedSurfaceSlugs: ["carpet", "upholstery", "sealed-hardwood"],
    recommendedMethodSlugs: ["enzyme-cleaners", "absorption-and-extraction"],
    avoidMethodSlugs: ["high-heat-setting-without-removal"],
    recommendedToolSlugs: ["white-terry-towel", "extractor", "detail-brush"],
    avoidToolSlugs: ["dark-transfer-prone-towel"],
    visualSignals: ["yellowing", "tide rings", "persistent odor zone", "repeat spotting"],
    safetyNotes: [
      "Address moisture fully or odor can persist below the visible surface.",
      "Always blot before aggressive agitation on textiles.",
    ],
    professionalEscalationThresholds: [
      "odor persists after repeated treatment",
      "padding or subfloor contamination is likely",
      "large-area contamination exists",
    ],
    riskLevel: "medium-high",
  },
  {
    slug: "grout-soiling",
    name: "Grout Soiling",
    kind: "soil",
    summary:
      "Embedded soil and residue trapped in porous grout lines, often darkened by repeated moisture and foot traffic.",
    aliases: ["dirty grout", "embedded grout soil"],
    relatedArticleSlugs: ["how-to-clean-grout", "bathroom-cleaning-guide"],
    relatedServiceSlugs: ["bathroom-cleaning", "deep-cleaning"],
    category: "embedded porous soil",
    composition: ["tracked soil", "soap residue", "moisture-retained grime", "organic residue"],
    formsFrom: [
      "porous grout absorbing soil",
      "insufficient drying",
      "infrequent deep agitation",
    ],
    commonLocations: ["bathroom floors", "shower walls", "backsplashes", "kitchen tile floors"],
    affectedSurfaceSlugs: ["grout"],
    recommendedMethodSlugs: ["alkaline-cleaners", "oxidizing-cleaners", "mechanical-agitation"],
    avoidMethodSlugs: ["acid-on-cementitious-grout-without-need"],
    recommendedToolSlugs: ["grout-brush", "detail-brush", "microfiber-towel"],
    avoidToolSlugs: ["metal-scraper", "steel-wool"],
    visualSignals: ["darkened joints", "uneven grout color", "shadowed lines", "stained porous joints"],
    safetyNotes: [
      "Do not use aggressive chemistry that can damage grout integrity without a clear need.",
      "Use controlled moisture to avoid driving soil deeper.",
    ],
    professionalEscalationThresholds: [
      "grout is deteriorating or powdering",
      "deep staining does not release with standard methods",
      "sealing or restoration is needed after cleaning",
    ],
    riskLevel: "medium",
  },
];
