import type { SurfaceEntity } from "./types";

export const SURFACE_ENTITIES: SurfaceEntity[] = [
  {
    slug: "glass",
    name: "Glass",
    kind: "surface",
    summary:
      "A generally non-porous surface that shows mineral deposits, soap scum, haze, and streaking very easily.",
    aliases: ["window glass", "shower glass"],
    relatedArticleSlugs: ["how-to-clean-windows", "how-to-clean-shower", "how-to-remove-hard-water-stains"],
    relatedServiceSlugs: ["window-cleaning", "bathroom-cleaning"],
    materialFamily: "glass",
    finishTypes: ["clear", "tempered", "coated"],
    porosity: "non-porous",
    sensitivities: ["abrasion-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["acid-cleaners", "microfiber-cleaning", "mechanical-agitation"],
    avoidMethodSlugs: ["abrasive-scraping"],
    safeToolSlugs: ["microfiber-towel", "squeegee", "non-scratch-scrub-pad"],
    avoidToolSlugs: ["steel-wool", "metal-scraper"],
    commonProblemSlugs: ["soap-scum", "hard-water-stains"],
    maintenancePrinciples: [
      "remove mineral residue before polishing",
      "use clean low-lint towels",
      "keep residue and rinse water from drying on the surface",
    ],
    safetyNotes: [
      "Do not use abrasive tools that can scratch or haze the surface.",
      "Be cautious with coated specialty glass finishes.",
    ],
  },
  {
    slug: "ceramic-tile",
    name: "Ceramic Tile",
    kind: "surface",
    summary:
      "A durable finished tile surface that is generally water-tolerant but often paired with more sensitive grout joints.",
    aliases: ["tile"],
    relatedArticleSlugs: ["how-to-clean-grout", "how-to-clean-shower", "bathroom-cleaning-guide"],
    relatedServiceSlugs: ["bathroom-cleaning", "deep-cleaning"],
    materialFamily: "ceramic",
    finishTypes: ["gloss", "matte", "textured"],
    porosity: "low-porosity",
    sensitivities: ["abrasion-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["acid-cleaners", "alkaline-cleaners", "oxidizing-cleaners", "mechanical-agitation"],
    avoidMethodSlugs: ["abrasive-scraping"],
    safeToolSlugs: ["microfiber-towel", "grout-brush", "non-scratch-scrub-pad"],
    avoidToolSlugs: ["steel-wool", "metal-scraper"],
    commonProblemSlugs: ["soap-scum", "hard-water-stains", "mildew", "grout-soiling"],
    maintenancePrinciples: [
      "treat the tile face differently from the grout joints",
      "match chemistry to the residue type",
      "rinse thoroughly so soils are removed rather than redistributed",
    ],
    safetyNotes: [
      "Aggressive abrasion can dull decorative finishes.",
      "Always account for the grout and caulk surrounding the tile.",
    ],
  },
  {
    slug: "porcelain-tile",
    name: "Porcelain Tile",
    kind: "surface",
    summary:
      "A dense tile surface with strong cleaning tolerance, though finish type still matters for scratching and residue control.",
    aliases: ["porcelain"],
    relatedArticleSlugs: ["how-to-clean-shower", "how-to-clean-grout"],
    relatedServiceSlugs: ["bathroom-cleaning", "deep-cleaning"],
    materialFamily: "porcelain",
    finishTypes: ["gloss", "matte", "textured"],
    porosity: "low-porosity",
    sensitivities: ["abrasion-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["acid-cleaners", "alkaline-cleaners", "oxidizing-cleaners", "mechanical-agitation"],
    avoidMethodSlugs: ["abrasive-scraping"],
    safeToolSlugs: ["microfiber-towel", "grout-brush", "non-scratch-scrub-pad"],
    avoidToolSlugs: ["steel-wool", "metal-scraper"],
    commonProblemSlugs: ["soap-scum", "hard-water-stains", "mildew", "grout-soiling"],
    maintenancePrinciples: [
      "remove residue fully to avoid haze",
      "match tool aggression to finish texture",
      "treat joints and seams as separate cleaning zones",
    ],
    safetyNotes: [
      "Textured finishes can trap residue if rinsing is incomplete.",
      "Do not assume all porcelain can tolerate aggressive scraping.",
    ],
  },
  {
    slug: "fiberglass",
    name: "Fiberglass",
    kind: "surface",
    summary:
      "A bathroom surface that can accumulate soap scum and hard water but scratches more easily than tile or glass.",
    aliases: ["fiberglass tub", "fiberglass shower surround"],
    relatedArticleSlugs: ["how-to-clean-shower", "how-to-remove-soap-scum"],
    relatedServiceSlugs: ["bathroom-cleaning", "deep-cleaning"],
    materialFamily: "composite",
    finishTypes: ["gelcoat", "smooth"],
    porosity: "low-porosity",
    sensitivities: ["abrasion-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["acid-cleaners", "microfiber-cleaning", "mechanical-agitation"],
    avoidMethodSlugs: ["abrasive-scraping"],
    safeToolSlugs: ["microfiber-towel", "non-scratch-scrub-pad"],
    avoidToolSlugs: ["steel-wool", "metal-scraper", "stiff-grit-pad"],
    commonProblemSlugs: ["soap-scum", "hard-water-stains"],
    maintenancePrinciples: [
      "use non-scratch tools only",
      "avoid embedding abrasion into the finish",
      "fully rinse cleaning agents from the surface",
    ],
    safetyNotes: [
      "Abrasive tools can permanently dull or scratch gelcoat finishes.",
    ],
  },
  {
    slug: "chrome",
    name: "Chrome",
    kind: "surface",
    summary:
      "A reflective plated finish common on fixtures that shows spotting, haze, and abrasion easily.",
    aliases: ["chrome fixtures"],
    relatedArticleSlugs: ["how-to-remove-hard-water-stains", "bathroom-cleaning-guide"],
    relatedServiceSlugs: ["bathroom-cleaning"],
    materialFamily: "plated metal",
    finishTypes: ["polished"],
    porosity: "non-porous",
    sensitivities: ["abrasion-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["acid-cleaners", "microfiber-cleaning"],
    avoidMethodSlugs: ["abrasive-scraping"],
    safeToolSlugs: ["microfiber-towel", "non-scratch-scrub-pad"],
    avoidToolSlugs: ["steel-wool", "metal-scraper"],
    commonProblemSlugs: ["hard-water-stains", "soap-scum"],
    maintenancePrinciples: [
      "remove minerals gently before polishing dry",
      "use fresh towels to avoid re-streaking",
    ],
    safetyNotes: [
      "Do not use metal tools on plated finishes.",
    ],
  },
  {
    slug: "stainless-steel",
    name: "Stainless Steel",
    kind: "surface",
    summary:
      "A non-porous metal surface that resists many soils well but shows streaking, residue, and scratch direction.",
    aliases: ["stainless appliances", "stainless fixtures"],
    relatedArticleSlugs: ["how-to-clean-kitchen", "kitchen-cleaning-guide"],
    relatedServiceSlugs: ["kitchen-cleaning", "deep-cleaning"],
    materialFamily: "metal",
    finishTypes: ["brushed", "polished"],
    porosity: "non-porous",
    sensitivities: ["abrasion-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["alkaline-cleaners", "microfiber-cleaning"],
    avoidMethodSlugs: ["acid-cleaners", "abrasive-scraping"],
    safeToolSlugs: ["microfiber-towel", "non-scratch-scrub-pad"],
    avoidToolSlugs: ["steel-wool", "metal-scraper"],
    commonProblemSlugs: ["hard-water-stains", "kitchen-grease"],
    maintenancePrinciples: [
      "clean with the grain where visible",
      "remove degreaser residue fully",
      "avoid over-wetting seams and control panels",
    ],
    safetyNotes: [
      "Harsh acids and abrasive tools can damage finish appearance.",
    ],
  },
  {
    slug: "painted-cabinetry",
    name: "Painted Cabinetry",
    kind: "surface",
    summary:
      "A finish-sensitive kitchen surface that often collects grease and requires moisture-controlled cleaning.",
    aliases: ["painted cabinets", "cabinet faces"],
    relatedArticleSlugs: ["how-to-clean-greasy-kitchen-cabinets", "how-to-clean-kitchen"],
    relatedServiceSlugs: ["kitchen-cleaning", "deep-cleaning"],
    materialFamily: "painted wood composite",
    finishTypes: ["satin", "semi-gloss", "matte"],
    porosity: "variable",
    sensitivities: ["moisture-sensitive", "finish-sensitive", "abrasion-sensitive"],
    safeMethodSlugs: ["alkaline-cleaners", "microfiber-cleaning"],
    avoidMethodSlugs: ["overwetting-wood-finishes", "abrasive-scraping"],
    safeToolSlugs: ["microfiber-towel", "detail-brush"],
    avoidToolSlugs: ["steel-wool", "stiff-grit-pad", "metal-scraper"],
    commonProblemSlugs: ["kitchen-grease"],
    maintenancePrinciples: [
      "use controlled moisture only",
      "remove degreaser residue completely",
      "avoid aggressive friction on painted edges",
    ],
    safetyNotes: [
      "Over-wetting can swell seams or damage finish integrity.",
    ],
  },
  {
    slug: "laminate",
    name: "Laminate",
    kind: "surface",
    summary:
      "A common finished household surface that tolerates light cleaning well but can be damaged by seam saturation or abrasion.",
    aliases: ["laminate surfaces"],
    relatedArticleSlugs: ["how-to-clean-kitchen"],
    relatedServiceSlugs: ["kitchen-cleaning", "deep-cleaning"],
    materialFamily: "laminate composite",
    finishTypes: ["smooth", "textured"],
    porosity: "low-porosity",
    sensitivities: ["abrasion-sensitive", "moisture-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["alkaline-cleaners", "neutral-cleaners", "microfiber-cleaning"],
    avoidMethodSlugs: ["abrasive-scraping", "overwetting-wood-finishes"],
    safeToolSlugs: ["microfiber-towel", "non-scratch-scrub-pad"],
    avoidToolSlugs: ["steel-wool", "metal-scraper"],
    commonProblemSlugs: ["kitchen-grease"],
    maintenancePrinciples: [
      "control moisture around seams and edges",
      "avoid scratching decorative finishes",
    ],
    safetyNotes: [
      "Do not flood seams or use aggressive scraping.",
    ],
  },
  {
    slug: "grout",
    name: "Grout",
    kind: "surface",
    summary:
      "A porous joint material that holds onto soils, moisture, and discoloration more easily than adjacent tile.",
    aliases: ["tile grout", "cementitious grout"],
    relatedArticleSlugs: ["how-to-clean-grout", "how-to-clean-shower"],
    relatedServiceSlugs: ["bathroom-cleaning", "deep-cleaning"],
    materialFamily: "cementitious joint material",
    finishTypes: ["sealed", "unsealed"],
    porosity: "high-porosity",
    sensitivities: ["acid-sensitive", "moisture-sensitive", "abrasion-sensitive"],
    safeMethodSlugs: ["alkaline-cleaners", "oxidizing-cleaners", "mechanical-agitation"],
    avoidMethodSlugs: ["acid-on-cementitious-grout-without-need"],
    safeToolSlugs: ["grout-brush", "detail-brush", "microfiber-towel"],
    avoidToolSlugs: ["metal-scraper", "steel-wool"],
    commonProblemSlugs: ["grout-soiling", "mildew"],
    maintenancePrinciples: [
      "use controlled dwell time",
      "extract or remove suspended soil rather than flooding",
      "dry the area well after cleaning",
    ],
    safetyNotes: [
      "Repeated aggressive acid exposure can weaken grout over time.",
    ],
  },
  {
    slug: "caulk",
    name: "Caulk",
    kind: "surface",
    summary:
      "A flexible seam material prone to mildew staining and degradation if moisture issues persist.",
    aliases: ["bathroom caulk", "sealant"],
    relatedArticleSlugs: ["how-to-clean-shower"],
    relatedServiceSlugs: ["bathroom-cleaning", "deep-cleaning"],
    materialFamily: "sealant",
    finishTypes: ["silicone", "latex"],
    porosity: "variable",
    sensitivities: ["abrasion-sensitive", "chemical-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["oxidizing-cleaners", "microfiber-cleaning"],
    avoidMethodSlugs: ["abrasive-scraping"],
    safeToolSlugs: ["microfiber-towel", "detail-brush"],
    avoidToolSlugs: ["metal-scraper", "steel-wool"],
    commonProblemSlugs: ["mildew"],
    maintenancePrinciples: [
      "clean gently to preserve seam integrity",
      "prioritize drying and ventilation after cleaning",
    ],
    safetyNotes: [
      "Discolored or penetrated caulk may need replacement rather than repeated cleaning.",
    ],
  },
  {
    slug: "painted-drywall",
    name: "Painted Drywall",
    kind: "surface",
    summary:
      "A finish-sensitive wall surface that must be cleaned with controlled moisture and low abrasion.",
    aliases: ["painted walls"],
    relatedArticleSlugs: ["bathroom-cleaning-guide"],
    relatedServiceSlugs: ["deep-cleaning"],
    materialFamily: "painted gypsum wallboard",
    finishTypes: ["flat", "eggshell", "satin", "semi-gloss"],
    porosity: "variable",
    sensitivities: ["moisture-sensitive", "abrasion-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["neutral-cleaners", "microfiber-cleaning"],
    avoidMethodSlugs: ["acid-cleaners", "abrasive-scraping"],
    safeToolSlugs: ["microfiber-towel"],
    avoidToolSlugs: ["steel-wool", "stiff-grit-pad", "metal-scraper"],
    commonProblemSlugs: ["mildew"],
    maintenancePrinciples: [
      "use minimal moisture",
      "blot rather than over-scrub where finish is delicate",
    ],
    safetyNotes: [
      "Do not saturate drywall-backed assemblies.",
    ],
  },
  {
    slug: "carpet",
    name: "Carpet",
    kind: "surface",
    summary:
      "A porous fiber surface that traps soils and moisture deeply, making odor and stain removal more complex.",
    aliases: ["carpet fibers"],
    relatedArticleSlugs: ["how-to-remove-pet-stains"],
    relatedServiceSlugs: ["deep-cleaning"],
    materialFamily: "textile flooring",
    finishTypes: ["cut pile", "loop", "synthetic", "blended"],
    porosity: "high-porosity",
    sensitivities: ["moisture-sensitive", "stain-prone", "abrasion-sensitive"],
    safeMethodSlugs: ["enzyme-cleaners", "absorption-and-extraction"],
    avoidMethodSlugs: ["high-heat-setting-without-removal"],
    safeToolSlugs: ["white-terry-towel", "extractor", "detail-brush"],
    avoidToolSlugs: ["metal-scraper", "dark-transfer-prone-towel"],
    commonProblemSlugs: ["pet-stains"],
    maintenancePrinciples: [
      "blot and extract rather than oversaturate",
      "fully dry after treatment",
      "treat odor source depth, not just the visible surface",
    ],
    safetyNotes: [
      "Excess moisture can wick soils and cause repeat spotting.",
    ],
  },
  {
    slug: "upholstery",
    name: "Upholstery",
    kind: "surface",
    summary:
      "A textile furnishing surface that requires residue control, colorfastness awareness, and careful moisture handling.",
    aliases: ["fabric upholstery"],
    relatedArticleSlugs: ["how-to-remove-pet-stains"],
    relatedServiceSlugs: ["deep-cleaning"],
    materialFamily: "textile furnishing",
    finishTypes: ["woven", "synthetic", "blended"],
    porosity: "high-porosity",
    sensitivities: ["moisture-sensitive", "stain-prone", "abrasion-sensitive"],
    safeMethodSlugs: ["enzyme-cleaners", "absorption-and-extraction"],
    avoidMethodSlugs: ["high-heat-setting-without-removal"],
    safeToolSlugs: ["white-terry-towel", "detail-brush", "extractor"],
    avoidToolSlugs: ["metal-scraper", "dark-transfer-prone-towel"],
    commonProblemSlugs: ["pet-stains"],
    maintenancePrinciples: [
      "test for colorfastness",
      "blot and lift rather than grind stain deeper",
      "dry thoroughly after spot treatment",
    ],
    safetyNotes: [
      "Fabric instability or dye transfer may require professional treatment.",
    ],
  },
  {
    slug: "sealed-hardwood",
    name: "Sealed Hardwood",
    kind: "surface",
    summary:
      "A finish-protected wood surface that still requires moisture control and non-aggressive cleaning methods.",
    aliases: ["hardwood floors", "finished wood floors"],
    relatedArticleSlugs: ["how-to-clean-hardwood-floors"],
    relatedServiceSlugs: ["deep-cleaning"],
    materialFamily: "finished wood",
    finishTypes: ["urethane", "factory-finished", "site-finished"],
    porosity: "variable",
    sensitivities: ["moisture-sensitive", "abrasion-sensitive", "finish-sensitive"],
    safeMethodSlugs: ["neutral-cleaners", "microfiber-cleaning"],
    avoidMethodSlugs: ["acid-cleaners", "alkaline-cleaners", "high-heat-setting-without-removal"],
    safeToolSlugs: ["microfiber-towel", "mop-pad"],
    avoidToolSlugs: ["steam-machine", "steel-wool", "metal-scraper"],
    commonProblemSlugs: ["pet-stains"],
    maintenancePrinciples: [
      "keep moisture minimal",
      "avoid standing water",
      "use tools that do not abrade finish coats",
    ],
    safetyNotes: [
      "Heat and moisture can damage wood flooring systems.",
    ],
  },
];
