import type { ToolEntity } from "./types";

export const TOOL_ENTITIES: ToolEntity[] = [
  {
    slug: "microfiber-towel",
    name: "Microfiber Towel",
    kind: "tool",
    summary:
      "A versatile low-lint cleaning towel designed to lift and trap soils with reduced scratching when clean and properly used.",
    aliases: ["microfiber cloth"],
    relatedArticleSlugs: ["how-to-clean-windows", "how-to-clean-kitchen", "how-to-clean-shower"],
    relatedServiceSlugs: ["bathroom-cleaning", "kitchen-cleaning", "window-cleaning"],
    category: "towel",
    materials: ["microfiber synthetic blend"],
    idealForSoilSlugs: ["soap-scum", "hard-water-stains", "kitchen-grease"],
    idealForSurfaceSlugs: [
      "glass",
      "ceramic-tile",
      "porcelain-tile",
      "fiberglass",
      "chrome",
      "stainless-steel",
      "painted-cabinetry",
      "laminate",
      "sealed-hardwood",
      "grout",
      "caulk",
      "painted-drywall",
    ],
    notRecommendedForSurfaceSlugs: [],
    usePrinciples: [
      "fold to create multiple clean working faces",
      "rotate frequently to prevent smear",
      "pair with the correct chemistry and drying pass",
    ],
    careInstructions: [
      "wash separately from lint-heavy fabrics",
      "avoid fabric softener",
      "replace when overloaded or worn",
    ],
    safetyNotes: ["Dirty microfiber redistributes soil instead of removing it."],
  },
  {
    slug: "white-terry-towel",
    name: "White Terry Towel",
    kind: "tool",
    summary:
      "A highly absorbent towel useful for blotting and moisture removal, especially on textile-related spot work.",
    aliases: ["white absorbent towel"],
    relatedArticleSlugs: ["how-to-remove-pet-stains"],
    relatedServiceSlugs: ["deep-cleaning"],
    category: "towel",
    materials: ["cotton terry"],
    idealForSoilSlugs: ["pet-stains"],
    idealForSurfaceSlugs: ["carpet", "upholstery"],
    notRecommendedForSurfaceSlugs: ["glass"],
    usePrinciples: [
      "blot rather than rub aggressively",
      "use white fabric to monitor transfer and avoid dye bleed risk",
    ],
    careInstructions: ["launder thoroughly after contamination exposure"],
    safetyNotes: ["Discard or isolate heavily contaminated towels after use."],
  },
  {
    slug: "dark-transfer-prone-towel",
    name: "Dark Transfer-Prone Towel",
    kind: "tool",
    summary:
      "A towel category that should be avoided on sensitive textiles because dye transfer risk can complicate stain removal.",
    aliases: ["colored towel"],
    relatedArticleSlugs: [],
    relatedServiceSlugs: [],
    category: "towel",
    materials: ["dyed fabric"],
    idealForSoilSlugs: [],
    idealForSurfaceSlugs: [],
    notRecommendedForSurfaceSlugs: ["carpet", "upholstery"],
    usePrinciples: ["do not use for stain work on porous light-colored fabrics"],
    careInstructions: [],
    safetyNotes: ["Can create secondary staining."],
  },
  {
    slug: "grout-brush",
    name: "Grout Brush",
    kind: "tool",
    summary:
      "A narrow stiff-bristle brush designed to concentrate agitation inside grout lines and narrow joints.",
    aliases: ["tile grout brush"],
    relatedArticleSlugs: ["how-to-clean-grout", "how-to-clean-shower"],
    relatedServiceSlugs: ["bathroom-cleaning", "deep-cleaning"],
    category: "brush",
    materials: ["synthetic bristles", "plastic handle"],
    idealForSoilSlugs: ["grout-soiling", "mildew", "soap-scum"],
    idealForSurfaceSlugs: ["grout", "ceramic-tile", "porcelain-tile"],
    notRecommendedForSurfaceSlugs: ["fiberglass", "painted-drywall"],
    usePrinciples: [
      "let chemistry dwell before brushing",
      "scrub the joint rather than the decorative surface when possible",
    ],
    careInstructions: [
      "rinse after use",
      "replace when bristles deform or load with residue",
    ],
    safetyNotes: ["Too much force can damage weak or deteriorated grout."],
  },
  {
    slug: "detail-brush",
    name: "Detail Brush",
    kind: "tool",
    summary:
      "A small cleaning brush used for corners, seams, edges, and fixtures where larger tools lack precision.",
    aliases: ["detail cleaning brush"],
    relatedArticleSlugs: ["how-to-clean-kitchen", "how-to-clean-shower"],
    relatedServiceSlugs: ["bathroom-cleaning", "kitchen-cleaning"],
    category: "brush",
    materials: ["synthetic bristles", "plastic handle"],
    idealForSoilSlugs: ["mildew", "kitchen-grease", "grout-soiling"],
    idealForSurfaceSlugs: ["grout", "caulk", "chrome", "painted-cabinetry", "carpet", "upholstery"],
    notRecommendedForSurfaceSlugs: [],
    usePrinciples: [
      "use for controlled agitation in tight areas",
      "avoid excessive pressure on delicate finishes",
    ],
    careInstructions: ["clean residue from bristles after use"],
    safetyNotes: [
      "Cross-contamination can occur if used between biological and food-contact areas without cleaning.",
    ],
  },
  {
    slug: "non-scratch-scrub-pad",
    name: "Non-Scratch Scrub Pad",
    kind: "tool",
    summary:
      "A low-abrasion pad used to increase friction on bonded soils without the aggression of metal tools.",
    aliases: ["non-scratch pad"],
    relatedArticleSlugs: ["how-to-remove-soap-scum", "how-to-clean-kitchen"],
    relatedServiceSlugs: ["bathroom-cleaning", "kitchen-cleaning"],
    category: "pad",
    materials: ["synthetic non-scratch fiber"],
    idealForSoilSlugs: ["soap-scum", "hard-water-stains", "kitchen-grease"],
    idealForSurfaceSlugs: ["glass", "fiberglass", "ceramic-tile", "porcelain-tile", "stainless-steel", "laminate"],
    notRecommendedForSurfaceSlugs: ["painted-drywall", "sealed-hardwood"],
    usePrinciples: [
      "pair with softened soil, not dry aggressive scrubbing",
      "test if finish sensitivity is uncertain",
    ],
    careInstructions: ["replace once loaded or roughened"],
    safetyNotes: [
      "Non-scratch does not mean safe on every finish under all pressure levels.",
    ],
  },
  {
    slug: "squeegee",
    name: "Squeegee",
    kind: "tool",
    summary:
      "A water-removal tool used to pull rinse water and residue off smooth surfaces before spotting and streaking can form.",
    aliases: ["glass squeegee"],
    relatedArticleSlugs: ["how-to-clean-windows", "how-to-clean-shower"],
    relatedServiceSlugs: ["window-cleaning", "bathroom-cleaning"],
    category: "squeegee",
    materials: ["rubber blade", "plastic or metal handle"],
    idealForSoilSlugs: ["soap-scum", "hard-water-stains"],
    idealForSurfaceSlugs: ["glass", "chrome", "ceramic-tile", "porcelain-tile"],
    notRecommendedForSurfaceSlugs: ["grout", "caulk", "carpet", "upholstery"],
    usePrinciples: [
      "use after soil and chemistry are removed",
      "wipe blade regularly to avoid drag lines",
    ],
    careInstructions: ["replace worn blades", "keep blade edge clean and straight"],
    safetyNotes: ["A damaged blade can leave streaks or chatter marks."],
  },
  {
    slug: "extractor",
    name: "Extractor",
    kind: "tool",
    summary:
      "A moisture-removal machine or device used to pull liquid and suspended contamination out of porous materials.",
    aliases: ["spot extractor"],
    relatedArticleSlugs: ["how-to-remove-pet-stains"],
    relatedServiceSlugs: ["deep-cleaning"],
    category: "extractor",
    materials: ["vacuum extraction system"],
    idealForSoilSlugs: ["pet-stains"],
    idealForSurfaceSlugs: ["carpet", "upholstery"],
    notRecommendedForSurfaceSlugs: ["sealed-hardwood"],
    usePrinciples: [
      "extract after chemistry has had time to work",
      "repeat until moisture and residue recovery improve",
    ],
    careInstructions: [
      "clean recovery system after use",
      "do not store contaminated liquid in the machine",
    ],
    safetyNotes: [
      "Improper use can overwet textile systems or drive moisture deeper.",
    ],
  },
  {
    slug: "mop-pad",
    name: "Mop Pad",
    kind: "tool",
    summary:
      "A controlled-distribution floor cleaning pad used for light moisture maintenance and residue pickup.",
    aliases: ["flat mop pad"],
    relatedArticleSlugs: ["how-to-clean-hardwood-floors"],
    relatedServiceSlugs: ["deep-cleaning"],
    category: "mop",
    materials: ["microfiber pad"],
    idealForSoilSlugs: [],
    idealForSurfaceSlugs: ["sealed-hardwood", "laminate"],
    notRecommendedForSurfaceSlugs: ["carpet", "upholstery"],
    usePrinciples: [
      "keep pads clean and only lightly damp where moisture sensitivity exists",
    ],
    careInstructions: ["launder after use"],
    safetyNotes: [
      "A dirty or overwet mop pad can leave residue and excess moisture behind.",
    ],
  },
  {
    slug: "steel-wool",
    name: "Steel Wool",
    kind: "tool",
    summary:
      "A highly abrasive metal tool that is usually inappropriate for finish preservation on residential cleaning surfaces.",
    aliases: ["abrasive steel pad"],
    relatedArticleSlugs: [],
    relatedServiceSlugs: [],
    category: "pad",
    materials: ["steel fiber"],
    idealForSoilSlugs: [],
    idealForSurfaceSlugs: [],
    notRecommendedForSurfaceSlugs: [
      "glass",
      "fiberglass",
      "chrome",
      "stainless-steel",
      "painted-cabinetry",
      "laminate",
      "grout",
      "caulk",
      "painted-drywall",
      "sealed-hardwood",
    ],
    usePrinciples: ["avoid use on residential finish-sensitive surfaces"],
    careInstructions: [],
    safetyNotes: [
      "Can scratch, shed metal particles, and permanently damage finishes.",
    ],
  },
  {
    slug: "metal-scraper",
    name: "Metal Scraper",
    kind: "tool",
    summary:
      "A sharp-edge tool that carries high damage risk on most household surfaces when used for routine residue removal.",
    aliases: ["razor scraper"],
    relatedArticleSlugs: [],
    relatedServiceSlugs: [],
    category: "scraper",
    materials: ["metal blade"],
    idealForSoilSlugs: [],
    idealForSurfaceSlugs: [],
    notRecommendedForSurfaceSlugs: [
      "glass",
      "fiberglass",
      "chrome",
      "stainless-steel",
      "painted-cabinetry",
      "laminate",
      "grout",
      "caulk",
      "painted-drywall",
      "sealed-hardwood",
      "carpet",
      "upholstery",
    ],
    usePrinciples: [
      "not recommended for standard household finish-preservation cleaning flows",
    ],
    careInstructions: [],
    safetyNotes: ["Can gouge, scratch, chip, or cut surfaces and sealants."],
  },
  {
    slug: "steam-machine",
    name: "Steam Machine",
    kind: "tool",
    summary:
      "A heat-and-moisture cleaning device that can be effective in some contexts but is unsafe on certain finishes and assemblies.",
    aliases: ["steam cleaner"],
    relatedArticleSlugs: [],
    relatedServiceSlugs: [],
    category: "steam-machine",
    materials: ["heated vapor device"],
    idealForSoilSlugs: [],
    idealForSurfaceSlugs: ["ceramic-tile", "porcelain-tile"],
    notRecommendedForSurfaceSlugs: ["sealed-hardwood", "painted-cabinetry", "laminate", "caulk"],
    usePrinciples: [
      "only use where heat and moisture are clearly compatible with the surface system",
    ],
    careInstructions: ["maintain according to manufacturer guidance"],
    safetyNotes: [
      "Heat and moisture can damage finishes, seams, and adhesives.",
    ],
  },
  {
    slug: "stiff-grit-pad",
    name: "Stiff Grit Pad",
    kind: "tool",
    summary:
      "A high-friction abrasive pad that is too aggressive for many residential finish-sensitive surfaces.",
    aliases: ["abrasive scrub pad"],
    relatedArticleSlugs: [],
    relatedServiceSlugs: [],
    category: "pad",
    materials: ["abrasive fiber"],
    idealForSoilSlugs: [],
    idealForSurfaceSlugs: [],
    notRecommendedForSurfaceSlugs: [
      "fiberglass",
      "chrome",
      "stainless-steel",
      "painted-cabinetry",
      "laminate",
      "painted-drywall",
    ],
    usePrinciples: ["avoid use where finish preservation matters"],
    careInstructions: [],
    safetyNotes: ["Can visibly dull or scratch surfaces quickly."],
  },
];
