/**
 * Raw Amazon catalog (authoritative authored source). Runtime consumers use
 * `getAllAmazonCatalogImports()` / `getAmazonCatalogImportBySlug()` so image URLs are
 * normalized, deduped, and primary is lifted from the gallery when needed.
 * Keep rows sorted by brand, then slug.
 */
import type { AmazonCatalogImportRecord } from "./amazonCatalogTypes";

export const AMAZON_CATALOG_IMPORT: AmazonCatalogImportRecord[] = [
  {
    slug: "3m-adhesive-remover",
    asin: "B00ZIM9XPI",
    amazonUrl: "https://www.amazon.com/dp/B00ZIM9XPI",
    amazonAffiliateUrl: "",
    brand: "3M",
    primaryImageUrl: "https://m.media-amazon.com/images/I/4174csuxF7L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/4174csuxF7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41sdPvstRjL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51Xpu6ru4wL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/31uuS2HI89L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "active-washing-machine-cleaner-tablets",
    asin: "B08DVFZTTG",
    amazonUrl: "https://www.amazon.com/dp/B08DVFZTTG",
    amazonAffiliateUrl: "",
    brand: "Active",
    primaryImageUrl: "https://m.media-amazon.com/images/I/810RmF7vESL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/810RmF7vESL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81BRzK8mOEL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81ROAg8vJdL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "affresh-washing-machine-cleaner",
    asin: "B00C91Q86I",
    amazonUrl: "https://www.amazon.com/dp/B00C91Q86I",
    amazonAffiliateUrl: "",
    brand: "Affresh",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61FQYzDVFxL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61FQYzDVFxL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71DqckKi7UL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71LtA9xKOlL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "bar-keepers-friend-cleanser",
    asin: "B000V72992",
    amazonUrl: "https://www.amazon.com/dp/B000V72992",
    amazonAffiliateUrl: "",
    brand: "Bar Keepers Friend",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71AHharn3CL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71AHharn3CL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71nXZZBPzkL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/8193WuWPB4L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/8148V6MsiBL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "biokleen-bac-out-stain-odor-remover",
    asin: "B08HPKV83L",
    amazonUrl: "https://www.amazon.com/dp/B08HPKV83L",
    amazonAffiliateUrl: "",
    brand: "Biokleen",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41byFVHXksL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41byFVHXksL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/310TBTe-0WL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51Q4C8ueZSS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51ZcPvjgNGS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41mG9eD5WVS._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "bona-hardwood-floor-cleaner",
    asin: "B07GC6N35C",
    amazonUrl: "https://www.amazon.com/dp/B07GC6N35C",
    amazonAffiliateUrl: "",
    brand: "Bona",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71msibe7EHL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71msibe7EHL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71msibe7EHL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "bona-hard-surface-floor-cleaner",
    asin: "B079SMTFVN",
    amazonUrl: "https://www.amazon.com/dp/B079SMTFVN",
    amazonAffiliateUrl: "",
    brand: "Bona",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41TH5QxqlJL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41TH5QxqlJL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/810e3Ga4S3L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "cerama-bryte-cooktop-cleaner",
    asin: "B001TI570A",
    amazonUrl: "https://www.amazon.com/dp/B001TI570A",
    amazonAffiliateUrl: "",
    brand: "Cerama Bryte",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71gfNhZEkBL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71gfNhZEkBL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71haoFMmYFL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "oxiclean-versatile-stain-remover",
    asin: "B00QKIHOY6",
    amazonUrl: "https://www.amazon.com/dp/B00QKIHOY6",
    amazonAffiliateUrl: "",
    brand: "Church & Dwight",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71dpECz9hQL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71dpECz9hQL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71f44XVQwTL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/8106JOEWKwL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81AyMAByM-L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "clorox-clean-up-cleaner-bleach",
    asin: "B0009P68MK",
    amazonUrl: "https://www.amazon.com/dp/B0009P68MK",
    amazonAffiliateUrl: "",
    brand: "Clorox",
    primaryImageUrl: "https://m.media-amazon.com/images/I/6159J1+M4lL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/6159J1+M4lL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61EFEalSHSL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61QF+tlBaKL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61vrUDz8R-L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71aBXRjEBmL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "clorox-disinfecting-wipes",
    asin: "B0009PCOF0",
    amazonUrl: "https://www.amazon.com/dp/B0009PCOF0",
    amazonAffiliateUrl: "",
    brand: "Clorox",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41FbnXyNzoL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41FbnXyNzoL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41sG-Pf0ssL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51aVyMCGqZL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51GjFYxKpIL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "clorox-laundry-sanitizer",
    asin: "B0CFW47JPY",
    amazonUrl: "https://www.amazon.com/dp/B0CFW47JPY",
    amazonAffiliateUrl: "",
    brand: "Clorox",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71Tie9EG2nL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71Tie9EG2nL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Vbt0rX-1L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71b6Wm1Uk7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71mkWTrhofL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71uhNuktQ5L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "clorox-toilet-bowl-cleaner-bleach",
    asin: "B00006IELT",
    amazonUrl: "https://www.amazon.com/dp/B00006IELT",
    amazonAffiliateUrl: "",
    brand: "Clorox",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41h8lujbfAL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41h8lujbfAL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51kZyw1BUJL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41fivTWUZ+L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41R09WoyskL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "pine-sol-original-multi-surface-cleaner",
    asin: "B007ZT4LTU",
    amazonUrl: "https://www.amazon.com/dp/B007ZT4LTU",
    amazonAffiliateUrl: "",
    brand: "Clorox",
    primaryImageUrl: "https://m.media-amazon.com/images/I/81TMXH1CyUL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/81TMXH1CyUL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81wIU-USStL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71QCo3PslgL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41AXZ+S9+VL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "clr-calcium-lime-rust",
    asin: "B0CLX1TGS7",
    amazonUrl: "https://www.amazon.com/dp/B0CLX1TGS7",
    amazonAffiliateUrl: "",
    brand: "CLR",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61MqKhHCVOL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61MqKhHCVOL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/8165EbJP7jL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/818Qf186fkL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81GcDC-VZLL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "concrobium-mold-control",
    asin: "B000UVGHQK",
    amazonUrl: "https://www.amazon.com/dp/B000UVGHQK",
    amazonAffiliateUrl: "",
    brand: "Concrobium",
    primaryImageUrl: "https://m.media-amazon.com/images/I/616ORJJd55L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/616ORJJd55L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51mrhTLgrEL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51pmfpe3j8L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41J1dRUvk3L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51OSCznfdIL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "dawn-platinum-dish-spray",
    asin: "B0F1ZBWFYG",
    amazonUrl: "https://www.amazon.com/dp/B0F1ZBWFYG",
    amazonAffiliateUrl: "",
    brand: "Dawn",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71zJJunZD7L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71zJJunZD7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/811cz4Qp8VL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81F2bljhxPL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81SCMk4oyiL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "drano-max-gel-drain-clog-remover",
    asin: "B000BOB71G",
    amazonUrl: "https://www.amazon.com/dp/B000BOB71G",
    amazonAffiliateUrl: "",
    brand: "Drano",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41zFC680N0L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41zFC680N0L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/513xPiBPPkL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51JvX0DycBL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51iSJ6EAbFL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "easy-off-heavy-duty-oven-cleaner",
    asin: "B001FA1D82",
    amazonUrl: "https://www.amazon.com/dp/B001FA1D82",
    amazonAffiliateUrl: "",
    brand: "Easy-Off",
    primaryImageUrl: "https://m.media-amazon.com/images/I/51aCbRutSQL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/51aCbRutSQL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/418fUlfxfhL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Y8aJ58NsL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Qk5Q7u89L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "easy-off-kitchen-degreaser",
    asin: "B06XX85RSS",
    amazonUrl: "https://www.amazon.com/dp/B06XX85RSS",
    amazonAffiliateUrl: "",
    brand: "Easy-Off",
    primaryImageUrl: "https://m.media-amazon.com/images/I/51hRlYuqwxL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/51hRlYuqwxL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51oKhYtZPCL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61AU2JwqqzL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71n8wbDWYSL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "febreze-fabric-refresher-antimicrobial",
    asin: "B09NF53YVQ",
    amazonUrl: "https://www.amazon.com/dp/B09NF53YVQ",
    amazonAffiliateUrl: "",
    brand: "Febreze",
    primaryImageUrl: "https://m.media-amazon.com/images/I/412Gpb5F11L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/412Gpb5F11L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41CDbjyg4NL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41JkmILXitL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51FD62XS95L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Ueuf7AgXL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "fiebings-saddle-soap",
    asin: "B008ROOES0",
    amazonUrl: "https://www.amazon.com/dp/B008ROOES0",
    amazonAffiliateUrl: "",
    brand: "Fiebing's",
    primaryImageUrl: "https://m.media-amazon.com/images/I/614ONe6rwJL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/614ONe6rwJL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/614ONe6rwJL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "finish-dishwasher-cleaner",
    asin: "B010OVNPEW",
    amazonUrl: "https://www.amazon.com/dp/B010OVNPEW",
    amazonAffiliateUrl: "",
    brand: "Finish",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71+XZsFkp7L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71+XZsFkp7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/816THHAXrXL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81S21dVZMlL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "folex-instant-carpet-spot-remover",
    asin: "B001B0V5GG",
    amazonUrl: "https://www.amazon.com/dp/B001B0V5GG",
    amazonAffiliateUrl: "",
    brand: "Folex",
    primaryImageUrl: "https://m.media-amazon.com/images/I/711k-G8nFpL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/711k-G8nFpL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71BnSC6QouL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/31TKuAyKcIL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/313bXTbF+aL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "fresh-wave-odor-removing-spray",
    asin: "B07FGGC8G1",
    amazonUrl: "https://www.amazon.com/dp/B07FGGC8G1",
    amazonAffiliateUrl: "",
    brand: "Fresh Wave",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41EsgASZDSL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41EsgASZDSL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41wB6EJviFL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51rwSawMhSL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41wDoPYHgYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/31hPgFawWPL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "glisten-dishwasher-cleaner",
    asin: "B003PESG6S",
    amazonUrl: "https://www.amazon.com/dp/B003PESG6S",
    amazonAffiliateUrl: "",
    brand: "Glisten",
    primaryImageUrl: "https://m.media-amazon.com/images/I/714u98sZYLL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/714u98sZYLL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71TyYiw4vzL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/8123AT2WVWL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "goo-gone-original-liquid",
    asin: "B00006IBNJ",
    amazonUrl: "https://www.amazon.com/dp/B00006IBNJ",
    amazonAffiliateUrl: "",
    brand: "Goo Gone",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71EP0YX05TL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71EP0YX05TL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61Q+5BN-i0L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71F24cM9tML._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71QNOEBYZSL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "granite-gold-daily-cleaner",
    asin: "B01MZ10EKN",
    amazonUrl: "https://www.amazon.com/dp/B01MZ10EKN",
    amazonAffiliateUrl: "",
    brand: "Granite Gold",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71odrMhVK-L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71odrMhVK-L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71ZZiQT5TCL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71YlEJaeI0L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81a7QDuCAoL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/111mHoVK0kL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "goo-gone-spray-gel",
    asin: "B0F1DXKQRS",
    amazonUrl: "https://www.amazon.com/dp/B0F1DXKQRS",
    amazonAffiliateUrl: "",
    brand: "Goo Gone",
    primaryImageUrl: "https://m.media-amazon.com/images/I/414ktX1DYyL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/414ktX1DYyL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Cnv62ZF1L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Vb7KBAjlL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51UxfRBcjpL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51V2OWRlw9L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "goof-off-professional-strength-remover",
    asin: "B002MPPYYS",
    amazonUrl: "https://www.amazon.com/dp/B002MPPYYS",
    amazonAffiliateUrl: "",
    brand: "Goof Off",
    primaryImageUrl: "https://m.media-amazon.com/images/I/418J7wS1y6L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/418J7wS1y6L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81SKYCXZtbL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71IYz-Js2JL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41CagFfbFSL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "heinz-distilled-white-vinegar-5pct",
    asin: "B005OL9K42",
    amazonUrl: "https://www.amazon.com/dp/B005OL9K42",
    amazonAffiliateUrl: "",
    brand: "Heinz",
    primaryImageUrl: "https://m.media-amazon.com/images/I/81Jwqg+4i4L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/81Jwqg+4i4L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/11lzP6frduL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/8191DY9Sa4L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/31Zje3ab-hL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "drill-brush-power-scrubber-kit",
    asin: "B0D66LZTXZ",
    amazonUrl: "https://www.amazon.com/dp/B0D66LZTXZ",
    amazonAffiliateUrl: "",
    brand: "Holikme",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61cCKH7gtKL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61cCKH7gtKL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/7188Fda-7iL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71jw7wUlPaL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81F11kx9bsL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "hope-s-perfect-stainless-steel-cleaner",
    asin: "B00EWJA0QY",
    amazonUrl: "https://www.amazon.com/dp/B00EWJA0QY",
    amazonAffiliateUrl: "",
    brand: "HOPE'S",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71FpMIr1QaL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71FpMIr1QaL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/814HneFZ3oL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81F2kOhIZ9L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "impresa-descaler",
    asin: "B0C7LL8DZV",
    amazonUrl: "https://www.amazon.com/dp/B0C7LL8DZV",
    amazonAffiliateUrl: "",
    brand: "Impresa",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71+9o4ONnZL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71+9o4ONnZL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71UBpR7RWBL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71kXwaXn2tL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "invisible-glass-premium-glass-cleaner",
    asin: "B000M3V95U",
    amazonUrl: "https://www.amazon.com/dp/B000M3V95U",
    amazonAffiliateUrl: "",
    brand: "Invisible Glass",
    primaryImageUrl: "https://m.media-amazon.com/images/I/914DdQs5mxL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/914DdQs5mxL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/519q3nf5vKL._AC_SL1000_.jpg",
      "https://m.media-amazon.com/images/I/41fSnFo9wAL.jpg",
      "https://m.media-amazon.com/images/I/41AGhsWI-bL.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "krud-kutter-kitchen-degreaser",
    asin: "B082MRWN3W",
    amazonUrl: "https://www.amazon.com/dp/B082MRWN3W",
    amazonAffiliateUrl: "",
    brand: "Krud Kutter",
    primaryImageUrl: "https://m.media-amazon.com/images/I/717SHujLiML._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/717SHujLiML._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71TT1hi-DgL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71V1RslveSL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61z7In024LL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61vo-qTXrpL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "krud-kutter-original-cleaner-degreaser",
    asin: "B000S8EQFO",
    amazonUrl: "https://www.amazon.com/dp/B000S8EQFO",
    amazonAffiliateUrl: "",
    brand: "Krud Kutter",
    primaryImageUrl: "https://m.media-amazon.com/images/I/712RGdq5qBL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/712RGdq5qBL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71MNtJlJJUL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71NDoYhRgIL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71UF0GyxdGL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "lime-a-way-cleaner",
    asin: "B00949ZKYO",
    amazonUrl: "https://www.amazon.com/dp/B00949ZKYO",
    amazonAffiliateUrl: "",
    brand: "Lime-A-Way",
    primaryImageUrl: "https://m.media-amazon.com/images/I/713xb00f81L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/713xb00f81L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Ow5iv2MVL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71VkF7M-MTL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71o426I7EzL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "liquid-plumr-clog-destroyer-plus-pipeguard",
    asin: "B08245TL2X",
    amazonUrl: "https://www.amazon.com/dp/B08245TL2X",
    amazonAffiliateUrl: "",
    brand: "Liquid-Plumr",
    primaryImageUrl: "https://m.media-amazon.com/images/I/51Rz5cjY1IL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/51Rz5cjY1IL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41dTrSZWWfL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Xw9INdduL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81ufME+08XL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "lysol-disinfectant-spray",
    asin: "B007RFQA64",
    amazonUrl: "https://www.amazon.com/dp/B007RFQA64",
    amazonAffiliateUrl: "",
    brand: "Lysol",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61Mv+yDnM7L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61Mv+yDnM7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61O66xFJYtL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61Qs4RCM51L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71BJV+yX7mL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71C+7XEOY9L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "lysol-laundry-sanitizer",
    asin: "B09TZ7RKFW",
    amazonUrl: "https://www.amazon.com/dp/B09TZ7RKFW",
    amazonAffiliateUrl: "",
    brand: "Lysol",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41f04Aja62L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41f04Aja62L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Vbt0rX-1L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71+pQyfGkiL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71K7naS+VsL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "lysol-power-bathroom-cleaner",
    asin: "B0BX7B5KJ3",
    amazonUrl: "https://www.amazon.com/dp/B0BX7B5KJ3",
    amazonAffiliateUrl: "",
    brand: "Lysol",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41bES3ldw4L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41bES3ldw4L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51ZWirB5xlL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51eXAZLYwjL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51PnpUYqqNL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41Rs9Hw95tL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "lysol-power-toilet-bowl-cleaner",
    asin: "B0875T6Z11",
    amazonUrl: "https://www.amazon.com/dp/B0875T6Z11",
    amazonAffiliateUrl: "",
    brand: "Lysol",
    primaryImageUrl: "https://m.media-amazon.com/images/I/81UAl6wUXrL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/81UAl6wUXrL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81btfjcfzYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61+-tSJpGUS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/31Ftj0cjn-L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "method-all-purpose-cleaner",
    asin: "B000EEX7QG",
    amazonUrl: "https://www.amazon.com/dp/B000EEX7QG",
    amazonAffiliateUrl: "",
    brand: "Method",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71+d9aLzrAL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71+d9aLzrAL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71fMpbCXzkL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81PTdwr3ybL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81kiNLtal2L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "method-daily-shower-spray",
    asin: "B00O4ZMASC",
    amazonUrl: "https://www.amazon.com/dp/B00O4ZMASC",
    amazonAffiliateUrl: "",
    brand: "Method",
    primaryImageUrl: "https://m.media-amazon.com/images/I/31ToU9eIoOS._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/31ToU9eIoOS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/21jBlEFXQzL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/21G6v3YZ0yL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/31BI4hIozcS._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "method-heavy-duty-degreaser",
    asin: "B06ZZF3FV2",
    amazonUrl: "https://www.amazon.com/dp/B06ZZF3FV2",
    amazonAffiliateUrl: "",
    brand: "Method",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41esFY5LqdS._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41esFY5LqdS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/31lhjNKZIEL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51vZZM2H7uS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51bnwtsUk6S._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "method-wood-for-good-daily-clean",
    asin: "B09LKN6LVH",
    amazonUrl: "https://www.amazon.com/dp/B09LKN6LVH",
    amazonAffiliateUrl: "",
    brand: "Method",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41PFi4ZlF7L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41PFi4ZlF7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41SQN1bGl1L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41X8AYvUmaL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41weSH4XTYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41E4QAr284L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "microban-24-hour-disinfectant-sanitizing-spray",
    asin: "B0FG345WYC",
    amazonUrl: "https://www.amazon.com/dp/B0FG345WYC",
    amazonAffiliateUrl: "",
    brand: "Microban",
    primaryImageUrl: "https://m.media-amazon.com/images/I/51pJBq67yIL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/51pJBq67yIL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41aLododwqL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/518bRUxZdDL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51uv8RECxnL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "murphy-oil-soap-wood-cleaner",
    asin: "B00005UVD7",
    amazonUrl: "https://www.amazon.com/dp/B00005UVD7",
    amazonAffiliateUrl: "",
    brand: "Murphy Oil Soap",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61ODrG94RRL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61ODrG94RRL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61ODrG94RRL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "natures-miracle-stain-and-odor-remover",
    asin: "B071W6CQ7S",
    amazonUrl: "https://www.amazon.com/dp/B071W6CQ7S",
    amazonAffiliateUrl: "",
    brand: "Nature's Miracle",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41aQu1qdnxL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41aQu1qdnxL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41AT0FDVVcL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41L6Wkhw7hL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51ePaOrPeiL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "odoban-disinfectant-odor-eliminator",
    asin: "B08J8F5N71",
    amazonUrl: "https://www.amazon.com/dp/B08J8F5N71",
    amazonAffiliateUrl: "",
    brand: "OdoBan",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41R13dJIWWL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41R13dJIWWL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41B7Kay5x2L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41ZxBG3WAXL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/511wDquj7kL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51A4GmK7qDL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "odoban-fabric-laundry-spray",
    asin: "B09MZSSM2F",
    amazonUrl: "https://www.amazon.com/dp/B09MZSSM2F",
    amazonAffiliateUrl: "",
    brand: "OdoBan",
    primaryImageUrl: "https://m.media-amazon.com/images/I/81b8Fwn2T1L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/81b8Fwn2T1L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81GAyAv7b2L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91ApPv2r8KL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91zmVsHQfqL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "oil-eater-cleaner-degreaser",
    asin: "B000EALHHG",
    amazonUrl: "https://www.amazon.com/dp/B000EALHHG",
    amazonAffiliateUrl: "",
    brand: "Oil Eater",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71F4gJcIxOL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71F4gJcIxOL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71MWYcmwCBL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81S0VCFINIL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81ZKc4Qr52L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "oxiclean-max-force-spray",
    asin: "B00KAKUN3E",
    amazonUrl: "https://www.amazon.com/dp/B00KAKUN3E",
    amazonAffiliateUrl: "",
    brand: "OxiClean",
    primaryImageUrl: "https://m.media-amazon.com/images/I/412cxdQ2lgL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/412cxdQ2lgL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41khRcF1xPL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41jWHhawmiL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51OS9uNDr6L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "pledge-multisurface-cleaner",
    asin: "B0021LZSJO",
    amazonUrl: "https://www.amazon.com/dp/B0021LZSJO",
    amazonAffiliateUrl: "",
    brand: "Pledge",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61AYY4zg9vL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61AYY4zg9vL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71r0PKbV4oL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71s1iV4S8IL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81GGKV5ZnBL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "purple-power-industrial-strength-cleaner-degreaser",
    asin: "B07F3SNQXW",
    amazonUrl: "https://www.amazon.com/dp/B07F3SNQXW",
    amazonAffiliateUrl: "",
    brand: "Purple Power",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41OMuMKrmoL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41OMuMKrmoL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51GehVJSpBL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51VvbHAZC7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41hRxT9WmkL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41zLArUxwJL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "rejuvenate-luxury-vinyl-floor-cleaner",
    asin: "B079Q77KJR",
    amazonUrl: "https://www.amazon.com/dp/B079Q77KJR",
    amazonAffiliateUrl: "",
    brand: "Rejuvenate",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41poYirhgfL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41poYirhgfL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51hNC2wFUML._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41PXnVc+AkL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/416YFmQQAuL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "resolve-carpet-cleaner-spray",
    asin: "B011O2T8A0",
    amazonUrl: "https://www.amazon.com/dp/B011O2T8A0",
    amazonAffiliateUrl: "",
    brand: "Resolve",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61-Kc8gViUL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61-Kc8gViUL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/616Hjhy1z3L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71UNPjzP9GL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/819kTWrziFL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "rocco-roxie-stain-odor-eliminator",
    asin: "B00CKFL93K",
    amazonUrl: "https://www.amazon.com/dp/B00CKFL93K",
    amazonAffiliateUrl: "",
    brand: "Rocco & Roxie Supply Co.",
    primaryImageUrl: "https://m.media-amazon.com/images/I/611T5GXwQXL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/611T5GXwQXL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41V0N+UY9NL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41ojiTLryAL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51uSGWcJEdL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "rubbermaid-microfiber-cleaning-cloths",
    asin: "B09YHVX1GT",
    amazonUrl: "https://www.amazon.com/dp/B09YHVX1GT",
    amazonAffiliateUrl: "",
    brand: "Rubbermaid",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71sGAO0pn0L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71sGAO0pn0L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/811PUKc-XKL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61w5X3xG1SL._AC_SL1347_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "scrubbing-bubbles-bathroom-grime-fighter",
    asin: "B00EEZKX2W",
    amazonUrl: "https://www.amazon.com/dp/B00EEZKX2W",
    amazonAffiliateUrl: "",
    brand: "Scrubbing Bubbles",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71BDd6Wk4FL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71BDd6Wk4FL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81j0UDTKFwL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61CgdGmXrtL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61Gq1lWej8L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "scrubbing-bubbles-daily-shower-cleaner",
    asin: "B016WFFGCI",
    amazonUrl: "https://www.amazon.com/dp/B016WFFGCI",
    amazonAffiliateUrl: "",
    brand: "Scrubbing Bubbles",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71+TiaIMxYL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71+TiaIMxYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71PHObTWFAL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71UL5qJvOuL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81TLJxajESL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "seventh-generation-all-purpose-cleaner",
    asin: "B0BB3H17Z4",
    amazonUrl: "https://www.amazon.com/dp/B0BB3H17Z4",
    amazonAffiliateUrl: "",
    brand: "Seventh Generation",
    primaryImageUrl: "https://m.media-amazon.com/images/I/618xRAsMF8L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/618xRAsMF8L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71cUXl-rjAL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/815pT+yu7ML._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81CcXHbDs9L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "seventh-generation-disinfecting-multi-surface-cleaner",
    asin: "B00BX9NPXQ",
    amazonUrl: "https://www.amazon.com/dp/B00BX9NPXQ",
    amazonAffiliateUrl: "",
    brand: "Seventh Generation",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41fhlvULnnL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41fhlvULnnL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51qrX0+ETIL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81KhfU+eOvL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/019h+CPo68L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "simple-green-all-purpose-cleaner",
    asin: "B004E3L13O",
    amazonUrl: "https://www.amazon.com/dp/B004E3L13O",
    amazonAffiliateUrl: "",
    brand: "Simple Green",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61Ymfn-WD+L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61Ymfn-WD+L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61Ymfn-WD+L._AC_SL1000_.jpg",
      "https://m.media-amazon.com/images/I/41vkeFY-dHL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "simple-green-pro-hd",
    asin: "B07VZ179K7",
    amazonUrl: "https://www.amazon.com/dp/B07VZ179K7",
    amazonAffiliateUrl: "",
    brand: "Simple Green",
    primaryImageUrl: "https://m.media-amazon.com/images/I/31owafekFgL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/31owafekFgL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51J8kWEZUJL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51x7iHOG0yL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51umxyxjxDL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "sprayway-glass-cleaner",
    asin: "B0002MBV5O",
    amazonUrl: "https://www.amazon.com/dp/B0002MBV5O",
    amazonAffiliateUrl: "",
    brand: "Sprayway",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71-y2iWRFdL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71-y2iWRFdL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51RYZIS0+CL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71uEZHVq+EL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81YqGdRIAHL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "sprayway-stainless-steel-cleaner",
    asin: "B007W9CUQE",
    amazonUrl: "https://www.amazon.com/dp/B007W9CUQE",
    amazonAffiliateUrl: "",
    brand: "Sprayway",
    primaryImageUrl: "https://m.media-amazon.com/images/I/412QJnR9jNL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/412QJnR9jNL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/415jU5m7CVL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/31eDl7YIEuL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41U1oOS6TvL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51fzNfCy1oL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "stonetech-daily-cleaner",
    asin: "B00065W99O",
    amazonUrl: "https://www.amazon.com/dp/B00065W99O",
    amazonAffiliateUrl: "",
    brand: "StoneTech",
    primaryImageUrl: "https://m.media-amazon.com/images/I/81rKOiJfYBL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/81rKOiJfYBL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71odrMhVK-L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71ZZiQT5TCL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71YlEJaeI0L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/713mGjjc5lL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "swiffer-wetjet-cleaning-solution",
    asin: "B07DGPL4YN",
    amazonUrl: "https://www.amazon.com/dp/B07DGPL4YN",
    amazonAffiliateUrl: "",
    brand: "Swiffer",
    primaryImageUrl: "https://m.media-amazon.com/images/I/81jhMRPzCBL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/81jhMRPzCBL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81zKoi62kXL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "therapy-stainless-steel-cleaner-polish",
    asin: "B00L2P0KNO",
    amazonUrl: "https://www.amazon.com/dp/B00L2P0KNO",
    amazonAffiliateUrl: "",
    brand: "Therapy",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71evQu1f+uL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71evQu1f+uL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/519zNuJtqlL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "tilex-daily-shower-cleaner",
    asin: "B07P5P38X2",
    amazonUrl: "https://www.amazon.com/dp/B07P5P38X2",
    amazonAffiliateUrl: "",
    brand: "Tilex",
    primaryImageUrl: "https://m.media-amazon.com/images/I/81K+dgzyyDL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/81K+dgzyyDL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71rOhsFcelL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51QFieyo8uL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41USX4c7aFL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "un-du-adhesive-remover",
    asin: "B003TZQPTS",
    amazonUrl: "https://www.amazon.com/dp/B003TZQPTS",
    amazonAffiliateUrl: "",
    brand: "Un-Du",
    primaryImageUrl: "https://m.media-amazon.com/images/I/614jsHu3vuL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/614jsHu3vuL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61ItR9tFTXL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/417n4CfO8RL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41ylONuDkbL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/417fF-m4QrL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "dezcal-descaling-powder",
    asin: "B001Q4YR44",
    amazonUrl: "https://www.amazon.com/dp/B001Q4YR44",
    amazonAffiliateUrl: "",
    brand: "Urnex",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61-5IPnPdIL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61-5IPnPdIL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/612cxwsmqfL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71OLIQQPz9L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "urnex-coffee-machine-descaler",
    asin: "B00E1NPB3I",
    amazonUrl: "https://www.amazon.com/dp/B00E1NPB3I",
    amazonAffiliateUrl: "",
    brand: "Urnex",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61sBWIyKMzL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61sBWIyKMzL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41XnNyMw8nL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "weiman-gas-range-cleaner-degreaser",
    asin: "B06ZZ6BTNT",
    amazonUrl: "https://www.amazon.com/dp/B06ZZ6BTNT",
    amazonAffiliateUrl: "",
    brand: "Weiman",
    primaryImageUrl: "https://m.media-amazon.com/images/I/51YjzFNO1HL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/51YjzFNO1HL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41RCuV20TAL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/513EuOUgmEL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51rFbyAbi4L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "weiman-stainless-steel-cleaner-polish",
    asin: "B001F0QJYA",
    amazonUrl: "https://www.amazon.com/dp/B001F0QJYA",
    amazonAffiliateUrl: "",
    brand: "Weiman",
    primaryImageUrl: "https://m.media-amazon.com/images/I/81MrvxYPb7L._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/81MrvxYPb7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81QHfSiWCtL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81kX7SCV9vL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "wet-and-forget-shower-cleaner",
    asin: "B07GJV5SY7",
    amazonUrl: "https://www.amazon.com/dp/B07GJV5SY7",
    amazonAffiliateUrl: "",
    brand: "Wet & Forget",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71RH3hnxm7S._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71RH3hnxm7S._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81Psq-0usTL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81b7jSmVIEL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81dBgdu1RwL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "windex-original-glass-cleaner",
    asin: "B075NPQDTG",
    amazonUrl: "https://www.amazon.com/dp/B075NPQDTG",
    amazonAffiliateUrl: "",
    brand: "Windex",
    primaryImageUrl: "https://m.media-amazon.com/images/I/7170FKCSbWS._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/7170FKCSbWS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71QmAEhxBWS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Tg5ui4EaL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71mRtVAROFL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "zero-odor-eliminator-spray",
    asin: "B001J0C3O6",
    amazonUrl: "https://www.amazon.com/dp/B001J0C3O6",
    amazonAffiliateUrl: "",
    brand: "Zero Odor",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41cLIwBGMTL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41cLIwBGMTL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41oVLcy7wHL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41vAsGgcJJL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51VGBHVDRpL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51ZdviuWd6L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "zep-calcium-lime-rust-remover",
    asin: "B002RPVW80",
    amazonUrl: "https://www.amazon.com/dp/B002RPVW80",
    amazonAffiliateUrl: "",
    brand: "Zep",
    primaryImageUrl: "https://m.media-amazon.com/images/I/71BmkSgh1TL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/71BmkSgh1TL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81eWu8NgooL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "zep-neutral-ph-floor-cleaner",
    asin: "B00360DG9S",
    amazonUrl: "https://www.amazon.com/dp/B00360DG9S",
    amazonAffiliateUrl: "",
    brand: "Zep",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41HlFA0pdQL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41HlFA0pdQL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41xe26UP2ZL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51n7ThuiOoL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51wzGuRKzFL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51QT35eYc4L._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "zep-oven-and-grill-cleaner",
    asin: "B07HN94S65",
    amazonUrl: "https://www.amazon.com/dp/B07HN94S65",
    amazonAffiliateUrl: "",
    brand: "Zep",
    primaryImageUrl: "https://m.media-amazon.com/images/I/41dbRyMVvlL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/41dbRyMVvlL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41-RZIY3EOS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51ZXdZQkU7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/41LpNPsNmFL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51O-W-vVKXL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
  {
    slug: "zep-shower-tub-tile-cleaner",
    asin: "B07PB7S5FT",
    amazonUrl: "https://www.amazon.com/dp/B07PB7S5FT",
    amazonAffiliateUrl: "",
    brand: "Zep",
    primaryImageUrl: "https://m.media-amazon.com/images/I/61Iu9+wGBGL._AC_SL1500_.jpg",
    imageUrls: [
          "https://m.media-amazon.com/images/I/61Iu9+wGBGL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81+7LsMAOJL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51YYv09kF0L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51Ge8HFuUZL._AC_SL1500_.jpg",
    ],
    buyLabel: "Buy on Amazon",
    isPurchaseAvailable: true,
  },
];
