import type { ProductSeed } from "./productTypes";

export type { ProductSeed } from "./productTypes";

import { getAmazonCatalogImportBySlug } from "./amazonCatalogRegistry";

function withAmazonDefaults(seed: ProductSeed): ProductSeed {
  return {
    ...seed,
    amazonUrl: seed.amazonUrl ?? "",
    amazonAffiliateUrl: seed.amazonAffiliateUrl ?? "",
    isPurchaseAvailable: seed.isPurchaseAvailable ?? false,
    buyLabel: seed.buyLabel ?? "Buy on Amazon",
  };
}

const PURCHASE_READY = [
  // GLASS / SURFACES
  "windex-original-glass-cleaner",
  "sprayway-glass-cleaner",
  "invisible-glass-premium-glass-cleaner",

  // DEGREASERS
  "krud-kutter-original-cleaner-degreaser",
  "dawn-platinum-dish-spray",
  "simple-green-all-purpose-cleaner",

  // MINERAL / HARD WATER
  "clr-calcium-lime-rust",
  "lime-a-way-cleaner",

  // ABRASIVE / HEAVY CLEAN
  "bar-keepers-friend-cleanser",
  "comet-cleanser-powder",
  "bon-ami-cleanser",

  // ADHESIVE / RESIDUE
  "goo-gone-original-liquid",

  // STOVETOP / SPECIALTY
  "cerama-bryte-cooktop-cleaner",

  // DISINFECTING / GENERAL
  "lysol-all-purpose-cleaner",
  "clorox-clean-up-cleaner",
  "lysol-disinfectant-spray",
  "clorox-clean-up-cleaner-bleach",

  // FLOOR / MULTI
  "mr-clean-multi-surface-cleaner",
  "pledge-multisurface-cleaner",

  // BATHROOM
  "scrubbing-bubbles-bathroom-cleaner",
  "scrubbing-bubbles-daily-shower-cleaner",
  "wet-and-forget-shower-cleaner",
  "kaboom-foam-tastic-bathroom-cleaner",

  // DEGREASERS / KITCHEN (batch 2)
  "oil-eater-cleaner-degreaser",
  "easy-off-kitchen-degreaser",

  // MINERAL / SCALE (batch 2)
  "zep-calcium-lime-rust-remover",

  // STAINLESS / APPLIANCE / DESCALER (batch 3)
  "weiman-stainless-steel-cleaner-polish",
  "therapy-stainless-steel-cleaner-polish",
  "hope-s-perfect-stainless-steel-cleaner",
  "affresh-washing-machine-cleaner",
  "active-washing-machine-cleaner-tablets",
  "glisten-dishwasher-cleaner",
  "finish-dishwasher-cleaner",
  "urnex-coffee-machine-descaler",
  "dezcal-descaling-powder",
  "impresa-descaler",

  // FABRIC / FLOOR / WOOD / APC / TOOLS (batch 4)
  "oxiclean-versatile-stain-remover",
  "resolve-carpet-cleaner-spray",
  "fiebings-saddle-soap",
  "murphy-oil-soap-wood-cleaner",
  "method-all-purpose-cleaner",
  "seventh-generation-all-purpose-cleaner",
  "bona-hardwood-floor-cleaner",
  "swiffer-wetjet-cleaning-solution",
  "drill-brush-power-scrubber-kit",
  "rubbermaid-microfiber-cleaning-cloths",
] as const;

/** Catalog slug when the purchase list uses a different label than `PRODUCTS_RAW`. */
const PURCHASE_READY_SLUG_ALIASES: Partial<Record<(typeof PURCHASE_READY)[number], string>> = {
  "clorox-clean-up-cleaner": "clorox-clean-up-cleaner-bleach",
  "scrubbing-bubbles-bathroom-cleaner": "scrubbing-bubbles-bathroom-grime-fighter",
};

function purchaseReadySeedSlugSet(): Set<string> {
  const set = new Set<string>();
  for (const slug of PURCHASE_READY) {
    set.add(slug);
    const mapped = PURCHASE_READY_SLUG_ALIASES[slug];
    if (mapped) set.add(mapped);
  }
  return set;
}

const PURCHASE_READY_SEED_SLUGS = purchaseReadySeedSlugSet();

/** Amazon PDP when the row has no `amazonUrl` but is purchase-enabled. */
const PURCHASE_AMAZON_FALLBACK: Partial<Record<string, string>> = {
  "windex-original-glass-cleaner": "https://www.amazon.com/dp/B075NPQDTG",
  "sprayway-glass-cleaner": "https://www.amazon.com/dp/B0002MBV5O",
  "invisible-glass-premium-glass-cleaner": "https://www.amazon.com/dp/B000M3V95U",
  "krud-kutter-original-cleaner-degreaser": "https://www.amazon.com/dp/B000S8EQFO",
  "simple-green-all-purpose-cleaner": "https://www.amazon.com/dp/B004E3L13O",
  "lime-a-way-cleaner": "https://www.amazon.com/dp/B00949ZKYO",
  "goo-gone-original-liquid": "https://www.amazon.com/dp/B00006IBNJ",
  "scrubbing-bubbles-bathroom-grime-fighter": "https://www.amazon.com/dp/B00EEZKX2W",
  "weiman-stainless-steel-cleaner-polish": "https://www.amazon.com/dp/B001F0QJYA",
  "therapy-stainless-steel-cleaner-polish": "https://www.amazon.com/dp/B00L2P0KNO",
  "hope-s-perfect-stainless-steel-cleaner": "https://www.amazon.com/dp/B00EWJA0QY",
  "affresh-washing-machine-cleaner": "https://www.amazon.com/dp/B00C91Q86I",
  "active-washing-machine-cleaner-tablets": "https://www.amazon.com/dp/B08DVFZTTG",
  "glisten-dishwasher-cleaner": "https://www.amazon.com/dp/B003PESG6S",
  "finish-dishwasher-cleaner": "https://www.amazon.com/dp/B010OVNPEW",
  "urnex-coffee-machine-descaler": "https://www.amazon.com/dp/B00E1NPB3I",
  "dezcal-descaling-powder": "https://www.amazon.com/dp/B001Q4YR44",
  "impresa-descaler": "https://www.amazon.com/dp/B0C7LL8DZV",
};

export const PRODUCTS_RAW: ProductSeed[] = [
  {
    id: "bar_keepers_friend_cleanser",
    slug: "bar-keepers-friend-cleanser",
    name: "Bar Keepers Friend Cleanser",
    brand: "Bar Keepers Friend",
    category: "powder cleanser",
    chemicalClass: "acid",
    intent: "restore",
    surfaces: ["stainless steel", "tile", "glass", "ceramic", "porcelain", "chrome"],
    problems: ["mineral deposits", "rust stains", "discoloration", "burnt residue"],
    notes: "Oxalic-acid family powder; spot-test polished stone and colored grout.",
    amazonUrl: "https://www.amazon.com/dp/B000V72992",
    walmartUrl: "https://www.walmart.com/ip/BAR-KEEPERS-FRIEND-POWDER-21OZ/15026756",
  },
  {
    id: "dawn_platinum_dish_spray",
    slug: "dawn-platinum-dish-spray",
    name: "Dawn Platinum EZ-Squeeze Dish Spray",
    brand: "Procter & Gamble",
    category: "dish soap (spray)",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["stainless steel", "glass", "laminate", "tile", "plastic"],
    problems: ["grease buildup", "oil stains", "food residue", "sticky residue"],
    amazonUrl: "https://www.amazon.com/dp/B0F1ZBWFYG",
    walmartUrl:
      "https://www.walmart.com/ip/Dawn-Ultra-Platinum-EZ-Squeeze-Dish-Soap-Liquid-Dishwashing-Liquid-Grease-Removal-Fresh-Rain-24-3oz/1732966259",
  },
  {
    id: "clr_calcium_lime_rust",
    slug: "clr-calcium-lime-rust",
    name: "CLR Calcium, Lime & Rust Remover",
    brand: "CLR Brands",
    category: "acidic descaler (liquid)",
    chemicalClass: "acid",
    intent: "restore",
    surfaces: ["tile", "glass", "chrome", "stainless steel", "toilets", "porcelain"],
    problems: ["limescale", "mineral deposits", "hard water film", "rust stains"],
    notes: "Not for natural stone or damaged finishes; follow label and rinse thoroughly.",
    amazonUrl: "https://www.amazon.com/dp/B0CLX1TGS7",
    walmartUrl:
      "https://www.walmart.com/ip/CLR-Calcium-Lime-and-Rust-Remover-Multi-Use-Household-Cleaner-EPA-Safer-Choice-28-oz/14574716",
    homeDepotUrl: "https://www.homedepot.com/p/CLR-28-OZ-Ounce-Calcium-Lime-Rust-Remover-CL-12/100049980",
  },
  {
    id: "oxiclean_versatile_stain_remover",
    slug: "oxiclean-versatile-stain-remover",
    name: "OxiClean Versatile Stain Remover (powder)",
    brand: "Church & Dwight",
    category: "oxygen bleach (percarbonate)",
    chemicalClass: "oxygen_bleach",
    intent: "clean",
    surfaces: ["appliances", "tile", "grout", "general household surfaces"],
    problems: ["tannin stains", "mildew stains", "discoloration", "odor retention"],
    notes: "Use as directed; avoid mixing with chlorine bleach or acids.",
    amazonUrl: "https://www.amazon.com/dp/B00QKIHOY6",
    walmartUrl: "https://www.walmart.com/ip/OxiClean-Versatile-Stain-Remover-5-lb/19406200",
  },
  {
    id: "heinz_distilled_white_vinegar_5pct",
    slug: "heinz-distilled-white-vinegar-5pct",
    name: "Heinz Distilled White Vinegar (5% acidity)",
    brand: "Heinz",
    category: "household vinegar",
    chemicalClass: "acid",
    intent: "clean",
    surfaces: ["tile", "glass", "grout"],
    problems: ["hard water film", "soap residue", "soap scum", "odor retention"],
    notes:
      "Mild-acid reference only—not a substitute for formulated descalers on heavy scale; avoid stone and sensitive finishes.",
    amazonUrl: "https://www.amazon.com/dp/B005OL9K42",
    walmartUrl: "https://www.walmart.com/ip/Heinz-All-Natural-Distilled-White-Vinegar-5-Acidity-1-gal-Jug/13908042",
  },
  {
    id: "lysol_disinfectant_spray",
    slug: "lysol-disinfectant-spray",
    name: "Lysol Disinfectant Spray",
    brand: "Lysol",
    category: "disinfectant spray",
    chemicalClass: "disinfectant",
    intent: "disinfect",
    surfaces: ["plastic", "tile", "porcelain", "ceramic", "countertops", "general household surfaces"],
    problems: ["bacteria buildup", "mold growth", "odor retention", "biofilm"],
    notes: "EPA registration and contact time are label-specific; never mix with other chemicals.",
    amazonUrl: "https://www.amazon.com/dp/B007RFQA64",
  },
  {
    id: "windex_original_glass_cleaner",
    slug: "windex-original-glass-cleaner",
    name: "Windex Original Glass Cleaner",
    brand: "Windex",
    category: "glass cleaner",
    chemicalClass: "ammonia_blend",
    intent: "clean",
    surfaces: ["glass", "mirrors", "shower glass", "chrome"],
    problems: ["streaking", "dust buildup", "product residue"],
    notes: "Ammonia-based; avoid specialty-coated glass per manufacturer.",
  },
  {
    id: "scrubbing_bubbles_bathroom_grime_fighter",
    slug: "scrubbing-bubbles-bathroom-grime-fighter",
    name: "Scrubbing Bubbles Bathroom Grime Fighter",
    brand: "Scrubbing Bubbles",
    category: "bathroom cleaner",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["tile", "porcelain", "ceramic", "chrome", "bathtubs", "sinks", "shower glass", "toilets"],
    problems: ["soap scum", "soap residue", "mildew stains", "discoloration", "biofilm"],
    notes: "Bathroom soap-grime maintenance; use CLR-class descalers for heavy mineral scale on label-safe surfaces.",
    amazonUrl: "https://www.amazon.com/dp/B00EEZKX2W",
  },
  {
    id: "goo_gone_original_liquid",
    slug: "goo-gone-original-liquid",
    name: "Goo Gone Original Liquid",
    brand: "Goo Gone",
    category: "adhesive remover",
    chemicalClass: "solvent_blend",
    intent: "remove_residue",
    surfaces: ["metal", "plastic", "ceramic", "glass", "tile", "countertops"],
    problems: ["adhesive residue", "sticky residue", "wax buildup", "cooked-on residue"],
    notes: "Spot-test finishes; flammable—ventilation and away from ignition.",
  },
  {
    id: "clorox_toilet_bowl_cleaner_bleach",
    slug: "clorox-toilet-bowl-cleaner-bleach",
    name: "Clorox Toilet Bowl Cleaner with Bleach",
    brand: "Clorox",
    category: "toilet bowl cleaner",
    chemicalClass: "bleach",
    intent: "disinfect",
    surfaces: ["toilets", "porcelain"],
    problems: ["bacteria buildup", "mold growth", "mildew stains", "hard water stains", "discoloration"],
    notes: "Bleach-forward bowl product only; never mix with ammonia or other cleaners; not a whole-bathroom cleaner.",
  },
  {
    id: "lime_a_way_cleaner",
    slug: "lime-a-way-cleaner",
    name: "Lime-A-Way Bathroom Cleaner",
    brand: "Lime-A-Way",
    category: "acidic bathroom descaler (liquid)",
    chemicalClass: "acid",
    intent: "restore",
    surfaces: ["tile", "porcelain", "chrome", "shower glass", "ceramic", "sinks", "bathtubs", "toilets"],
    problems: ["limescale", "mineral deposits", "hard water stains", "calcium buildup", "rust stains", "soap scum"],
    notes: "Bathroom-focused acidic scale chemistry; incompatible with stone, bleach, and ammonia—confirm label and rinse.",
  },
  {
    id: "zep_calcium_lime_rust_remover",
    slug: "zep-calcium-lime-rust-remover",
    name: "Zep Calcium, Lime & Rust Stain Remover",
    brand: "Zep",
    category: "acidic descaler (commercial-style liquid)",
    chemicalClass: "acid",
    intent: "restore",
    surfaces: ["tile", "glass", "chrome", "stainless steel", "porcelain", "sinks", "bathtubs", "toilets", "shower glass"],
    problems: ["limescale", "mineral deposits", "hard water film", "rust stains", "calcium buildup", "hard water stains"],
    notes: "Strong descaler positioning; verify SDS; never mix with bleach or other cleaners.",
    amazonUrl: "https://www.amazon.com/dp/B002RPVW80",
  },
  {
    id: "lysol_power_toilet_bowl_cleaner",
    slug: "lysol-power-toilet-bowl-cleaner",
    name: "Lysol Power Toilet Bowl Cleaner",
    brand: "Lysol",
    category: "toilet bowl cleaner (acid)",
    chemicalClass: "acid",
    intent: "disinfect",
    surfaces: ["toilets", "porcelain"],
    problems: [
      "limescale",
      "hard water stains",
      "calcium buildup",
      "rust stains",
      "bacteria buildup",
      "mildew stains",
      "discoloration",
    ],
    notes: "Acid-bowl chemistry vs bleach-bowl products—never mix; label defines disinfect and acid exposure limits.",
  },
  {
    id: "krud_kutter_original_cleaner_degreaser",
    slug: "krud-kutter-original-cleaner-degreaser",
    name: "Krud Kutter Original Concentrated Cleaner/Degreaser",
    brand: "Krud Kutter",
    category: "degreaser (liquid concentrate)",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["stainless steel", "tile", "laminate", "metal", "countertops", "appliances", "painted surfaces"],
    problems: ["grease buildup", "oil stains", "food residue", "cooked-on grease", "adhesive residue"],
    notes: "Dilute per label; benchmark degreaser beyond dish-spray workflows; spot-test paint and coatings.",
  },
  {
    id: "method_heavy_duty_degreaser",
    slug: "method-heavy-duty-degreaser",
    name: "Method Heavy Duty Degreaser",
    brand: "Method",
    category: "degreaser spray",
    chemicalClass: "alkaline",
    intent: "clean",
    surfaces: ["stainless steel", "tile", "laminate", "countertops", "appliances"],
    problems: ["grease buildup", "oil stains", "food residue", "burnt residue"],
    notes: "Consumer alkaline degreaser; ventilation and label dwell for heavy grease films.",
  },
  {
    id: "simple_green_all_purpose_cleaner",
    slug: "simple-green-all-purpose-cleaner",
    name: "Simple Green All-Purpose Cleaner",
    brand: "Simple Green",
    category: "all-purpose cleaner (concentrate)",
    chemicalClass: "alkaline",
    intent: "clean",
    surfaces: ["countertops", "appliances", "tile", "floors", "plastic", "metal", "general household surfaces"],
    problems: ["grease buildup", "food residue", "soap residue", "dust buildup", "discoloration"],
    notes: "Dilution-dependent mainstream benchmark—not a substitute for registered disinfectants or heavy descalers.",
    amazonUrl: "https://www.amazon.com/dp/B004E3L13O",
  },
  {
    id: "sprayway_glass_cleaner",
    slug: "sprayway-glass-cleaner",
    name: "Sprayway Glass Cleaner (aerosol)",
    brand: "Sprayway",
    category: "glass cleaner (aerosol)",
    chemicalClass: "ammonia_blend",
    intent: "clean",
    surfaces: ["glass", "mirrors", "shower glass", "chrome"],
    problems: ["streaking", "dust buildup", "product residue"],
    notes: "Foaming aerosol; flammable propellant and ventilation matter; confirm variant chemistry on label.",
  },
  {
    id: "invisible_glass_premium_glass_cleaner",
    slug: "invisible-glass-premium-glass-cleaner",
    name: "Invisible Glass Premium Glass Cleaner",
    brand: "Invisible Glass",
    category: "glass cleaner (clarity-first)",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["glass", "mirrors", "shower glass", "chrome"],
    problems: ["streaking", "dust buildup", "product residue"],
    notes: "Ammonia-free positioning vs ammoniated glass cleaners; still verify specialty coatings.",
  },
  {
    id: "goof_off_professional_strength_remover",
    slug: "goof-off-professional-strength-remover",
    name: "Goof Off Professional Strength Remover",
    brand: "Goof Off",
    category: "adhesive remover (strong solvent)",
    chemicalClass: "solvent_blend",
    intent: "remove_residue",
    surfaces: ["metal", "glass", "tile", "countertops", "ceramic"],
    problems: ["adhesive residue", "sticky residue", "wax buildup", "cooked-on residue"],
    notes: "Stronger and riskier than citrus-style removers—spot test, ventilation, ignition control.",
  },
  {
    id: "3m_adhesive_remover",
    slug: "3m-adhesive-remover",
    name: "3M General Purpose Adhesive Cleaner",
    brand: "3M",
    category: "adhesive remover (specialty)",
    chemicalClass: "solvent_blend",
    intent: "remove_residue",
    surfaces: ["metal", "glass", "plastic", "painted surfaces", "tile"],
    problems: ["adhesive residue", "sticky residue", "wax buildup"],
    notes: "Tape/graphics specialty benchmark; plastics and paint demand careful testing.",
  },
  {
    id: "clorox_disinfecting_wipes",
    slug: "clorox-disinfecting-wipes",
    name: "Clorox Disinfecting Wipes",
    brand: "Clorox",
    category: "disinfecting wipes",
    chemicalClass: "disinfectant",
    intent: "disinfect",
    surfaces: ["plastic", "tile", "porcelain", "ceramic", "countertops", "appliances"],
    problems: ["bacteria buildup", "mold growth", "biofilm", "mildew stains"],
    notes: "Wipe workflow and wet contact time differ from spray; respect porous and delicate surfaces on label.",
  },
  {
    id: "seventh_generation_disinfecting_multi_surface_cleaner",
    slug: "seventh-generation-disinfecting-multi-surface-cleaner",
    name: "Seventh Generation Disinfecting Multi-Surface Cleaner",
    brand: "Seventh Generation",
    category: "disinfecting liquid cleaner",
    chemicalClass: "disinfectant",
    intent: "disinfect",
    surfaces: ["countertops", "plastic", "tile", "porcelain", "ceramic", "general household surfaces"],
    problems: ["bacteria buildup", "mold growth", "biofilm", "mildew stains", "odor retention"],
    notes: "Verify EPA registration and contact time on bottle; same process discipline as conventional disinfectants.",
  },
  {
    id: "seventh_generation_all_purpose_cleaner",
    slug: "seventh-generation-all-purpose-cleaner",
    name: "Seventh Generation All Purpose Cleaner (Lemon Chamomile)",
    brand: "Seventh Generation",
    category: "all-purpose spray cleaner",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["countertops", "tile", "plastic", "porcelain", "ceramic", "general household surfaces"],
    problems: ["grease buildup", "food residue", "light film", "dust buildup", "product residue"],
    notes: "Plant-forward APC lane for everyday hard-surface grime; verify label on stone and finished wood; not a disinfectant substitute.",
    amazonUrl: "https://www.amazon.com/dp/B0BB3H17Z4",
  },
  {
    id: "zep_shower_tub_tile_cleaner",
    slug: "zep-shower-tub-tile-cleaner",
    name: "Zep Shower, Tub & Tile Cleaner",
    brand: "Zep",
    category: "bathroom cleaner",
    chemicalClass: "alkaline",
    intent: "clean",
    surfaces: ["tile", "porcelain", "ceramic", "chrome", "bathtubs", "sinks", "shower glass", "toilets"],
    problems: ["soap scum", "soap residue", "hard water stains", "mildew stains", "discoloration", "biofilm"],
    notes: "Stronger bathroom maintenance than light foam sprays; heavy scale still needs compatible acid descaler.",
  },
  {
    id: "lysol_power_bathroom_cleaner",
    slug: "lysol-power-bathroom-cleaner",
    name: "Lysol Power Bathroom Cleaner",
    brand: "Lysol",
    category: "bathroom disinfecting cleaner",
    chemicalClass: "disinfectant",
    intent: "disinfect",
    surfaces: ["tile", "porcelain", "ceramic", "chrome", "bathtubs", "sinks", "shower glass"],
    problems: ["soap scum", "soap residue", "mildew stains", "bacteria buildup", "discoloration", "biofilm"],
    notes: "Bathroom disinfect + grime positioning per label; not interchangeable with bowl-only acids or bleach gels.",
  },
  {
    id: "oxiclean_max_force_spray",
    slug: "oxiclean-max-force-spray",
    name: "OxiClean Max Force Laundry Stain Remover Spray",
    brand: "OxiClean",
    category: "oxygen bleach stain spray",
    chemicalClass: "oxygen_bleach",
    intent: "clean",
    surfaces: ["plastic", "tile", "countertops", "appliances", "general household surfaces"],
    problems: ["tannin stains", "dye transfer", "discoloration", "food residue", "mildew stains"],
    notes: "Spray stain workflow vs powder soak; never mix with chlorine bleach; check color/fabric safety.",
  },
  {
    id: "granite_gold_daily_cleaner",
    slug: "granite-gold-daily-cleaner",
    name: "Granite Gold Daily Cleaner",
    brand: "Granite Gold",
    category: "stone daily cleaner",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["stone", "granite", "marble", "quartz", "sealed stone", "countertops"],
    problems: ["dust buildup", "dullness", "soap residue", "product residue", "floor residue"],
    notes: "pH-neutral stone routine cleaner—never substitute for descalers or degreasers on heavy soils.",
  },
  {
    id: "stonetech_daily_cleaner",
    slug: "stonetech-daily-cleaner",
    name: "StoneTech Daily Cleaner",
    brand: "StoneTech",
    category: "stone daily cleaner",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["stone", "granite", "marble", "tile", "quartz", "sealed stone", "countertops"],
    problems: ["dust buildup", "dullness", "soap residue", "product residue", "floor residue"],
    notes: "Daily stone maintenance; confirm sealer compatibility; avoid acid or abrasive overlap.",
  },
  {
    id: "bona_hardwood_floor_cleaner",
    slug: "bona-hardwood-floor-cleaner",
    name: "Bona Hardwood Floor Cleaner",
    brand: "Bona",
    category: "floor cleaner (wood)",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["hardwood floors", "sealed wood"],
    problems: ["floor residue", "dust buildup", "dullness", "product residue"],
    notes: "Wood-floor-specific; not for stone, carpet, or heavy grease.",
    amazonUrl: "https://www.amazon.com/dp/B07GC6N35C",
  },
  {
    id: "zep_neutral_ph_floor_cleaner",
    slug: "zep-neutral-ph-floor-cleaner",
    name: "Zep Neutral pH Floor Cleaner",
    brand: "Zep",
    category: "floor cleaner (neutral)",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["tile floors", "hardwood floors", "floors", "vinyl", "laminate"],
    problems: ["floor residue", "dust buildup", "soap residue", "dullness"],
    notes: "Neutral floor maintenance benchmark; dilute per label; not a descaler or disinfectant substitute.",
  },
  {
    id: "resolve_carpet_cleaner_spray",
    slug: "resolve-carpet-cleaner-spray",
    name: "Resolve Carpet Cleaner Spray",
    brand: "Resolve",
    category: "carpet spot cleaner",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["carpet", "upholstery"],
    problems: ["organic stains", "food residue", "tannin stains", "dye transfer"],
    notes: "Fiber spot treatment only; not for hard-surface grease, scale, or disinfection claims.",
    amazonUrl: "https://www.amazon.com/dp/B011O2T8A0",
  },
  {
    id: "folex_instant_carpet_spot_remover",
    slug: "folex-instant-carpet-spot-remover",
    name: "Folex Instant Carpet Spot Remover",
    brand: "Folex",
    category: "carpet spot cleaner",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["carpet", "upholstery"],
    problems: ["organic stains", "food residue", "tannin stains", "dye transfer"],
    notes: "Water-based spotter benchmark; test colorfastness; keep off hard-surface mineral work.",
  },
  {
    id: "fiebings_saddle_soap",
    slug: "fiebings-saddle-soap",
    name: "Fiebing's Saddle Soap",
    brand: "Fiebing's",
    category: "leather cleaner (saddle soap)",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["leather", "upholstery", "finished leather", "auto interior"],
    problems: ["product residue", "dullness", "organic stains", "dust buildup"],
    notes: "Leather and oiled-hide maintenance—test in a hidden area; not a fabric carpet spotter or mineral descaler.",
    amazonUrl: "https://www.amazon.com/dp/B008ROOES0",
  },
  {
    id: "natures_miracle_stain_and_odor_remover",
    slug: "natures-miracle-stain-and-odor-remover",
    name: "Nature's Miracle Stain & Odor Remover",
    brand: "Nature's Miracle",
    category: "enzyme stain and odor",
    chemicalClass: "enzyme",
    intent: "clean",
    surfaces: ["carpet", "upholstery", "tile", "floors", "countertops"],
    problems: ["urine", "pet odor", "organic stains", "odor retention", "bio-organic buildup"],
    notes: "Enzyme/biological soil specialist—ineffective framing for grease, mineral, or adhesive leadership.",
  },
  {
    id: "odoban_disinfectant_odor_eliminator",
    slug: "odoban-disinfectant-odor-eliminator",
    name: "OdoBan Disinfectant & Odor Eliminator",
    brand: "OdoBan",
    category: "disinfectant / odor hybrid (verify label)",
    chemicalClass: "disinfectant",
    intent: "disinfect",
    surfaces: ["tile", "plastic", "countertops", "garbage cans", "general household surfaces"],
    problems: ["odor retention", "bacteria buildup", "mildew stains", "disinfection", "mold growth"],
    notes: "Hybrid SKU—rank below dedicated disinfectants on pure disinfection; pair with enzyme products for organic pet soils.",
  },
  {
    id: "wet_and_forget_shower_cleaner",
    slug: "wet-and-forget-shower-cleaner",
    name: "Wet & Forget Shower Cleaner",
    brand: "Wet & Forget",
    category: "passive shower maintenance",
    chemicalClass: "surfactant",
    intent: "maintain",
    surfaces: ["shower glass", "tile", "porcelain", "ceramic", "chrome"],
    problems: ["preventive maintenance", "soap scum"],
    notes: "No-rinse maintenance positioning—not for active heavy grease, scale restoration, or same-day deep scrub expectations.",
    amazonUrl: "https://www.amazon.com/dp/B07GJV5SY7",
  },
  {
    id: "drano_max_gel_drain_clog_remover",
    slug: "drano-max-gel-drain-clog-remover",
    name: "Drano Max Gel Drain Clog Remover",
    brand: "Drano",
    category: "drain opener",
    chemicalClass: "caustic",
    intent: "restore",
    surfaces: ["drains"],
    problems: ["clog"],
    notes: "Drain-only chemistry—never use as a general surface cleaner; severe mix hazards with other chemicals.",
  },
  {
    id: "murphy_oil_soap_wood_cleaner",
    slug: "murphy-oil-soap-wood-cleaner",
    name: "Murphy Oil Soap Wood Cleaner",
    brand: "Colgate-Palmolive",
    category: "wood cleaner (oil soap)",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["sealed wood", "hardwood floors", "cabinets", "laminate"],
    problems: ["floor residue", "dust buildup", "dullness", "product residue"],
    notes: "Oil-soap routine care for sealed wood; not a mineral descaler, disinfectant, or wax-stripping restorer.",
    amazonUrl: "https://www.amazon.com/dp/B00005UVD7",
    walmartUrl: "https://www.walmart.com/ip/Murphy-Oil-Soap-Wood-Cleaner-Original-32-fl-oz/10309136",
  },
  {
    id: "swiffer_wetjet_cleaning_solution",
    slug: "swiffer-wetjet-cleaning-solution",
    name: "Swiffer WetJet Wood Floor Cleaning Solution Refill",
    brand: "Swiffer",
    category: "mop system cleaning solution (refill)",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["hardwood floors", "sealed wood", "finished wood"],
    problems: ["floor residue", "dust buildup", "light film", "product residue"],
    notes: "WetJet refill lane for labeled wood floors—requires compatible WetJet hardware; not a general carpet or stone program.",
    amazonUrl: "https://www.amazon.com/dp/B07DGPL4YN",
  },
  {
    id: "drill_brush_power_scrubber_kit",
    slug: "drill-brush-power-scrubber-kit",
    name: "Holikme Drill Brush Power Scrubber Attachment Kit",
    brand: "Holikme",
    category: "power scrub brush attachments (drill)",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["tile", "grout", "bathtubs", "showers", "porcelain", "ceramic", "glass", "countertops"],
    problems: ["soap scum", "grease buildup", "product residue", "discoloration", "biofilm"],
    notes: "Mechanical agitation multiplier—match bristle stiffness to the surface, keep rpm moderate, and pair with appropriate chemistry.",
    amazonUrl: "https://www.amazon.com/dp/B0D66LZTXZ",
  },
  {
    id: "rubbermaid_microfiber_cleaning_cloths",
    slug: "rubbermaid-microfiber-cleaning-cloths",
    name: "Rubbermaid Microfiber Cleaning Cloths (24-Pack)",
    brand: "Rubbermaid",
    category: "microfiber cleaning cloths",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["glass", "stainless steel", "countertops", "tile", "appliances", "general household surfaces"],
    problems: ["streaking", "light film", "dust buildup", "product residue"],
    notes: "Lint-reduced wiping and buffing—launder without softener; not a substitute for stain chemistry on set-in soils.",
    amazonUrl: "https://www.amazon.com/dp/B09YHVX1GT",
  },
  {
    id: "rejuvenate_luxury_vinyl_floor_cleaner",
    slug: "rejuvenate-luxury-vinyl-floor-cleaner",
    name: "Rejuvenate Luxury Vinyl Floor Cleaner",
    brand: "Rejuvenate",
    category: "floor cleaner (LVP/LVT)",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["vinyl", "luxury vinyl", "tile floors", "laminate"],
    problems: ["floor residue", "dust buildup", "dullness", "soap residue"],
    notes: "Vinyl-first floor maintenance; keep off carpet, drains, and heavy grease restoration jobs.",
    amazonUrl: "https://www.amazon.com/dp/B07MTQ6HLJ",
  },
  {
    id: "pine_sol_original_multi_surface_cleaner",
    slug: "pine-sol-original-multi-surface-cleaner",
    name: "Pine-Sol Original Multi-Surface Cleaner",
    brand: "Clorox",
    category: "multi-surface cleaner (disinfecting when used per label)",
    chemicalClass: "disinfectant",
    intent: "disinfect",
    surfaces: [
      "tile",
      "plastic",
      "garbage cans",
      "countertops",
      "floors",
      "general household surfaces",
      "porcelain",
    ],
    problems: ["bacteria buildup", "odor retention", "mildew stains", "disinfection", "floor residue", "mold growth"],
    notes: "EPA claims and dilution are label-specific; never mix with bleach or other products; not a grease specialist or descaler.",
    amazonUrl: "https://www.amazon.com/dp/B000UTF9AO",
  },
  {
    id: "easy_off_heavy_duty_oven_cleaner",
    slug: "easy-off-heavy-duty-oven-cleaner",
    name: "Easy-Off Heavy Duty Oven Cleaner",
    brand: "Easy-Off",
    category: "oven cleaner (caustic)",
    chemicalClass: "caustic",
    intent: "restore",
    surfaces: ["ovens", "grills"],
    problems: ["cooked-on grease", "burnt residue", "baked-on grease"],
    notes: "Oven-interior specialist only—severe fumes; never generalize to countertops, floors, or fiber.",
    amazonUrl: "https://www.amazon.com/dp/B001FA1D82",
  },
  {
    id: "clorox_clean_up_cleaner_bleach",
    slug: "clorox-clean-up-cleaner-bleach",
    name: "Clorox Clean-Up Cleaner + Bleach",
    brand: "Clorox",
    category: "bleach spray cleaner",
    chemicalClass: "bleach",
    intent: "disinfect",
    surfaces: ["countertops", "tile", "appliances", "stainless steel", "plastic", "porcelain"],
    problems: ["bacteria buildup", "mold growth", "disinfection", "mildew stains"],
    notes: "Spray bleach workflow—ventilation, no mixing, and acid-sensitive surfaces off-label.",
    amazonUrl: "https://www.amazon.com/dp/B0009P68MK",
  },
  {
    id: "rocco_roxie_stain_odor_eliminator",
    slug: "rocco-roxie-stain-odor-eliminator",
    name: "Rocco & Roxie Stain & Odor Eliminator",
    brand: "Rocco & Roxie Supply Co.",
    category: "enzyme stain and odor",
    chemicalClass: "enzyme",
    intent: "clean",
    surfaces: ["carpet", "upholstery", "tile", "floors", "countertops"],
    problems: ["urine", "pet odor", "organic stains", "odor retention", "bio-organic buildup"],
    notes: "Enzyme peer to Nature’s Miracle—dwell and sequencing matter; not for mineral scale or fryer grease.",
    amazonUrl: "https://www.amazon.com/dp/B00WF0RT12",
  },
  {
    id: "lysol_laundry_sanitizer",
    slug: "lysol-laundry-sanitizer",
    name: "Lysol Laundry Sanitizer",
    brand: "Lysol",
    category: "laundry sanitizer (additive)",
    chemicalClass: "disinfectant",
    intent: "disinfect",
    surfaces: ["laundry", "fabrics", "bedding", "towels", "delicates"],
    problems: ["disinfection", "bacteria buildup", "odor retention", "laundry odor", "laundry disinfection"],
    notes: "Rinse-cycle / fabric workflow per label—not a hard-surface default vs sprays or wipes.",
    amazonUrl: "https://www.amazon.com/dp/B07CSSPBM6",
  },
  {
    id: "simple_green_pro_hd",
    slug: "simple-green-pro-hd",
    name: "Simple Green Pro HD Heavy-Duty Cleaner",
    brand: "Simple Green",
    category: "heavy-duty degreaser (concentrate)",
    chemicalClass: "alkaline",
    intent: "clean",
    surfaces: ["stainless steel", "tile", "concrete", "appliances", "floors", "countertops"],
    problems: ["grease buildup", "cooked-on grease", "oil stains", "floor residue", "food residue"],
    notes: "Stronger degreasing than typical APC; dilute per label—still not a drain opener or stone-safe descaler.",
    amazonUrl: "https://www.amazon.com/dp/B0009YYM38",
  },
  {
    id: "liquid_plumr_clog_destroyer_plus_pipeguard",
    slug: "liquid-plumr-clog-destroyer-plus-pipeguard",
    name: "Liquid-Plumr Clog Destroyer Plus+ Pipeguard",
    brand: "Liquid-Plumr",
    category: "drain opener",
    chemicalClass: "caustic",
    intent: "restore",
    surfaces: ["drains"],
    problems: ["clog"],
    notes: "Drain-only caustic gel—same isolation rules as other drain openers; never as a surface cleaner.",
    amazonUrl: "https://www.amazon.com/dp/B003CP4VLQ",
  },
  {
    id: "method_daily_shower_spray",
    slug: "method-daily-shower-spray",
    name: "Method Daily Shower Spray",
    brand: "Method",
    category: "shower maintenance spray",
    chemicalClass: "surfactant",
    intent: "maintain",
    surfaces: ["shower glass", "tile", "porcelain", "ceramic", "chrome"],
    problems: ["preventive maintenance", "soap scum", "light film"],
    notes: "Daily active shower upkeep—stronger scrub expectations than passive no-rinse programs; not for mineral restoration.",
    amazonUrl: "https://www.amazon.com/dp/B000PKQ7Y0",
  },
  {
    id: "method_all_purpose_cleaner",
    slug: "method-all-purpose-cleaner",
    name: "Method All-Purpose Cleaner (Pink Grapefruit)",
    brand: "Method",
    category: "all-purpose spray cleaner",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["countertops", "tile", "plastic", "porcelain", "ceramic", "glass", "general household surfaces"],
    problems: ["grease buildup", "food residue", "light film", "dust buildup", "product residue"],
    notes: "Scented APC benchmark for sealed non-porous daily cleaning; confirm label guidance on stone and waxed wood.",
    amazonUrl: "https://www.amazon.com/dp/B000EEX7QG",
  },
  {
    id: "pledge_multisurface_cleaner",
    slug: "pledge-multisurface-cleaner",
    name: "Pledge Multisurface Cleaner",
    brand: "Pledge",
    category: "multisurface cleaner",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["cabinets", "finished wood", "sealed wood", "laminate", "countertops", "appliances"],
    problems: ["light dust", "light film", "dust buildup", "product residue"],
    notes: "Finished-wood and cabinet-safe dust/film pass—different role from oil-soap floor programs; not a floor-stripper or disinfectant default.",
    amazonUrl: "https://www.amazon.com/dp/B0021LZSJO",
  },
  {
    id: "weiman_gas_range_cleaner_degreaser",
    slug: "weiman-gas-range-cleaner-degreaser",
    name: "Weiman Gas Range Cleaner & Degreaser",
    brand: "Weiman",
    category: "range and cooktop degreaser",
    chemicalClass: "alkaline",
    intent: "clean",
    surfaces: ["cooktops", "range hoods", "stainless steel", "appliances"],
    problems: [
      "grease buildup",
      "greasy film",
      "kitchen grease film",
      "food residue",
      "light film",
      "light dust",
      "burnt residue",
    ],
    notes: "Cooktop and hood grease specialist—prefer over broad APC/degreasers on labeled gas-range workflows; not a drain or oven-fume product.",
    amazonUrl: "https://www.amazon.com/dp/B001F0A3N0",
  },
  {
    id: "zep_oven_and_grill_cleaner",
    slug: "zep-oven-and-grill-cleaner",
    name: "Zep Oven and Grill Cleaner",
    brand: "Zep",
    category: "oven/grill cleaner",
    chemicalClass: "caustic",
    intent: "restore",
    surfaces: ["ovens", "grills"],
    problems: ["baked-on grease", "cooked-on grease", "burnt residue"],
    notes: "Heavy baked-on peer to Easy-Off—fumes and label-only surfaces; isolate from counters and floors.",
    amazonUrl: "https://www.amazon.com/dp/B07KYG1X8R",
  },
  {
    id: "bona_hard_surface_floor_cleaner",
    slug: "bona-hard-surface-floor-cleaner",
    name: "Bona Hard-Surface Floor Cleaner",
    brand: "Bona",
    category: "floor cleaner (hard surface)",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["hard-surface floors", "tile floors", "vinyl", "luxury vinyl", "laminate", "ceramic"],
    problems: ["floor residue", "dust buildup", "dullness", "soap residue", "product residue"],
    notes: "Sealed hard-surface floor line—wins on tile/vinyl/LVT vs hardwood-specific Bona; not wood-oil or oven chemistry.",
    amazonUrl: "https://www.amazon.com/dp/B000ARW2VW",
  },
  {
    id: "biokleen_bac_out_stain_odor_remover",
    slug: "biokleen-bac-out-stain-odor-remover",
    name: "Biokleen Bac-Out Stain + Odor Remover",
    brand: "Biokleen",
    category: "enzyme stain and odor",
    chemicalClass: "enzyme",
    intent: "clean",
    surfaces: ["carpet", "upholstery", "tile", "floors", "countertops", "laundry"],
    problems: ["urine", "pet odor", "organic stains", "odor retention", "bio-organic buildup", "laundry odor"],
    notes: "Third enzyme anchor—live-culture positioning; same mix discipline as other biology SKUs.",
    amazonUrl: "https://www.amazon.com/dp/B0010XK5IW",
  },
  {
    id: "clorox_laundry_sanitizer",
    slug: "clorox-laundry-sanitizer",
    name: "Clorox Laundry Sanitizer",
    brand: "Clorox",
    category: "laundry sanitizer (additive)",
    chemicalClass: "disinfectant",
    intent: "disinfect",
    surfaces: ["laundry", "fabrics", "bedding", "towels", "delicates"],
    problems: ["laundry disinfection", "disinfection", "bacteria buildup", "odor retention", "laundry odor"],
    notes: "Fabric-cycle peer to Lysol Laundry Sanitizer—never a hard-surface spray substitute.",
    amazonUrl: "https://www.amazon.com/dp/B08G8FXW4K",
  },
  {
    id: "microban_24_hour_disinfectant_sanitizing_spray",
    slug: "microban-24-hour-disinfectant-sanitizing-spray",
    name: "Microban 24 Hour Disinfectant Sanitizing Spray",
    brand: "Microban",
    category: "disinfectant spray",
    chemicalClass: "disinfectant",
    intent: "disinfect",
    surfaces: ["plastic", "tile", "countertops", "porcelain", "ceramic", "general household surfaces", "appliances"],
    problems: ["bacteria buildup", "mold growth", "disinfection", "mildew stains", "odor retention"],
    notes: "Hard-surface disinfect spray lane—verify EPA label and contact time; not enzyme biology or drain chemistry.",
    amazonUrl: "https://www.amazon.com/dp/B084KQ8XTF",
  },
  {
    id: "easy_off_kitchen_degreaser",
    slug: "easy-off-kitchen-degreaser",
    name: "Easy-Off Kitchen Degreaser",
    brand: "Easy-Off",
    category: "kitchen degreaser",
    chemicalClass: "alkaline",
    intent: "clean",
    surfaces: ["cooktops", "range hoods", "stainless steel appliances"],
    problems: ["greasy film", "grease buildup", "food residue", "cooked-on grease", "light film"],
    notes: "Cooktop/hood degreaser—never for oven/grill baked-on (use oven SKUs); not a drain or fabric product.",
    amazonUrl: "https://www.amazon.com/dp/B06XX85RSS",
  },
  {
    id: "active_washing_machine_cleaner_tablets",
    slug: "active-washing-machine-cleaner-tablets",
    name: "Active Washing Machine Cleaner Tablets",
    brand: "Active",
    category: "washing machine cleaner (tablets)",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["washing machines", "washer interior", "laundry appliances"],
    problems: ["musty odor", "odor retention", "product residue", "mold growth"],
    notes: "Tablet cycle-clean workflow per label—appliance interior only; not a fabric softener substitute.",
    amazonUrl: "https://www.amazon.com/dp/B08DVFZTTG",
  },
  {
    id: "affresh_washing_machine_cleaner",
    slug: "affresh-washing-machine-cleaner",
    name: "Affresh Washing Machine Cleaner",
    brand: "Affresh",
    category: "washing machine cleaner (tablets)",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["washing machines", "washer interior", "laundry appliances"],
    problems: ["musty odor", "odor retention", "product residue", "biofilm"],
    notes: "OEM-style washer maintenance tablets; follow brand cycle instructions—never mix with bleach in the same cycle.",
    amazonUrl: "https://www.amazon.com/dp/B00C91Q86I",
  },
  {
    id: "dezcal_descaling_powder",
    slug: "dezcal-descaling-powder",
    name: "Urnex Dezcal Activated Scale Remover (Powder)",
    brand: "Urnex",
    category: "descaling powder (coffee equipment)",
    chemicalClass: "acid",
    intent: "restore",
    surfaces: ["coffee makers", "espresso machines", "kettles", "appliances"],
    problems: ["mineral deposits", "limescale", "hard water stains", "scale deposits"],
    notes: "Powder descaler for labeled coffee/heating equipment—rinse thoroughly; not interchangeable with tablet descalers.",
    amazonUrl: "https://www.amazon.com/dp/B001Q4YR44",
  },
  {
    id: "finish_dishwasher_cleaner",
    slug: "finish-dishwasher-cleaner",
    name: "Finish Dishwasher Cleaner Liquid",
    brand: "Finish",
    category: "dishwasher maintenance cleaner (liquid)",
    chemicalClass: "acid",
    intent: "clean",
    surfaces: ["dishwashers", "appliances"],
    problems: ["limescale", "grease buildup", "odor retention", "mineral deposits"],
    notes: "Dishwasher-internal liquid cleaner per label—do not use as a hand dish soap substitute.",
    amazonUrl: "https://www.amazon.com/dp/B010OVNPEW",
  },
  {
    id: "glisten_dishwasher_cleaner",
    slug: "glisten-dishwasher-cleaner",
    name: "Glisten Dishwasher Cleaner and Hardwater Spot Remover",
    brand: "Glisten",
    category: "dishwasher maintenance cleaner",
    chemicalClass: "acid",
    intent: "clean",
    surfaces: ["dishwashers", "appliances"],
    problems: ["limescale", "hard water stains", "water spots", "odor retention"],
    notes: "In-machine dishwasher cleaner workflow; confirm compatibility with stainless interiors per label.",
    amazonUrl: "https://www.amazon.com/dp/B003PESG6S",
  },
  {
    id: "hope_s_perfect_stainless_steel_cleaner",
    slug: "hope-s-perfect-stainless-steel-cleaner",
    name: "HOPE'S Perfect Stainless Steel Cleaner & Polish",
    brand: "HOPE'S",
    category: "stainless polish",
    chemicalClass: "stainless_polish",
    intent: "clean",
    surfaces: ["finished stainless", "stainless steel appliances", "stainless steel", "appliances"],
    problems: ["fingerprints", "surface haze", "light film", "streaking", "dullness"],
    notes: "Stainless appearance lane—US listing is a multi-bottle case pack; verify unit count before buying.",
    amazonUrl: "https://www.amazon.com/dp/B00EWJA0QY",
  },
  {
    id: "impresa_descaler",
    slug: "impresa-descaler",
    name: "Impresa Coffee Machine Descaler",
    brand: "Impresa",
    category: "descaling liquid (coffee equipment)",
    chemicalClass: "acid",
    intent: "restore",
    surfaces: ["coffee makers", "espresso machines", "kettles", "appliances"],
    problems: ["mineral deposits", "limescale", "hard water stains", "scale deposits"],
    notes: "Liquid descaler for labeled brewers—follow dose and rinse steps; not a Dezcal powder substitute.",
    amazonUrl: "https://www.amazon.com/dp/B0C7LL8DZV",
  },
  {
    id: "urnex_coffee_machine_descaler",
    slug: "urnex-coffee-machine-descaler",
    name: "Urnex CleanCup Descaling Solution",
    brand: "Urnex",
    category: "descaling liquid (coffee equipment)",
    chemicalClass: "acid",
    intent: "restore",
    surfaces: ["coffee makers", "espresso machines", "kettles", "appliances"],
    problems: ["mineral deposits", "limescale", "hard water stains", "scale deposits"],
    notes: "14 oz liquid descaler positioned for Keurig/drip per listing—still follow your machine manufacturer guidance.",
    amazonUrl: "https://www.amazon.com/dp/B00E1NPB3I",
  },
  {
    id: "weiman_stainless_steel_cleaner_polish",
    slug: "weiman-stainless-steel-cleaner-polish",
    name: "Weiman Stainless Steel Cleaner & Polish",
    brand: "Weiman",
    category: "stainless polish",
    chemicalClass: "stainless_polish",
    intent: "clean",
    surfaces: ["finished stainless", "stainless steel appliances", "stainless steel", "appliances"],
    problems: ["fingerprints", "surface haze", "light film", "streaking", "dullness", "product residue"],
    notes: "Appearance/finish lane—not for mineral scale, rust removal, or heavy baked-on carbon.",
    amazonUrl: "https://www.amazon.com/dp/B001F0QJYA",
  },
  {
    id: "method_wood_for_good_daily_clean",
    slug: "method-wood-for-good-daily-clean",
    name: "Method Wood for Good Daily Clean",
    brand: "Method",
    category: "wood daily cleaner",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["finished wood", "sealed wood", "cabinets"],
    problems: ["light dust", "light film", "dust buildup", "product residue"],
    notes: "Daily finished-wood/cabinet care—distinct from Murphy floor oil-soap positioning.",
    amazonUrl: "https://www.amazon.com/dp/B003IPQQGW",
  },
  {
    id: "tilex_daily_shower_cleaner",
    slug: "tilex-daily-shower-cleaner",
    name: "Tilex Daily Shower Cleaner",
    brand: "Tilex",
    category: "shower maintenance spray",
    chemicalClass: "surfactant",
    intent: "maintain",
    surfaces: ["shower glass", "tile", "porcelain", "ceramic", "chrome"],
    problems: ["preventive maintenance", "soap scum", "light film"],
    notes: "Active daily shower maintenance between passive Wet & Forget and scrubbing restorers.",
    amazonUrl: "https://www.amazon.com/dp/B000V9N3JQ",
  },
  {
    id: "odoban_fabric_laundry_spray",
    slug: "odoban-fabric-laundry-spray",
    name: "OdoBan Fabric & Laundry Spray",
    brand: "OdoBan",
    category: "fabric odor spray",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["laundry", "fabrics", "bedding", "towels", "upholstery", "delicates"],
    problems: ["laundry odor", "odor retention", "pet odor"],
    notes: "Fabric refresh lane—verify label; not a hard-surface disinfect substitute.",
    amazonUrl: "https://www.amazon.com/dp/B09MZSSM2F",
  },
  {
    id: "oil_eater_cleaner_degreaser",
    slug: "oil-eater-cleaner-degreaser",
    name: "Oil Eater Cleaner Degreaser",
    brand: "Oil Eater",
    category: "heavy degreaser",
    chemicalClass: "alkaline",
    intent: "clean",
    surfaces: ["exterior concrete", "concrete", "garbage cans", "appliances"],
    problems: ["oil stains", "grease buildup", "greasy film", "food residue"],
    notes: "Industrial-style degreaser for concrete and tough grease—dilute per label; not stone-safe default.",
    amazonUrl: "https://www.amazon.com/dp/B000EALHHG",
  },
  {
    id: "un_du_adhesive_remover",
    slug: "un-du-adhesive-remover",
    name: "Un-Du Adhesive Remover",
    brand: "Un-Du",
    category: "adhesive remover",
    chemicalClass: "solvent_blend",
    intent: "remove_residue",
    surfaces: ["plastic", "laminate", "painted surfaces", "glass"],
    problems: ["adhesive residue", "sticky residue"],
    notes: "Plastic-friendly light adhesive lane—spot-test finishes; not a heavy solvent replacement for all jobs.",
    amazonUrl: "https://www.amazon.com/dp/B000I6QKYW",
  },
  {
    id: "concrobium_mold_control",
    slug: "concrobium-mold-control",
    name: "Concrobium Mold Control",
    brand: "Concrobium",
    category: "mold control treatment",
    chemicalClass: "mold_control",
    intent: "clean",
    surfaces: ["tile", "shower glass", "porcelain", "ceramic", "grout", "drywall", "bathtubs"],
    problems: ["mold growth", "mildew stains", "mildew growth", "biofilm", "mold staining", "preventive maintenance"],
    notes: "Mold-maintenance specialist—EPA claims are label-specific; not enzyme urine chemistry or mineral acid work.",
    amazonUrl: "https://www.amazon.com/dp/B00186D8ME",
  },
  {
    id: "purple_power_industrial_strength_cleaner_degreaser",
    slug: "purple-power-industrial-strength-cleaner-degreaser",
    name: "Purple Power Industrial Strength Cleaner & Degreaser",
    brand: "Purple Power",
    category: "heavy-duty degreaser (concentrate)",
    chemicalClass: "alkaline",
    intent: "clean",
    surfaces: ["outdoor concrete", "exterior concrete", "concrete", "garbage cans", "appliances"],
    problems: ["oil stains", "grease buildup", "greasy film", "kitchen grease film", "food residue"],
    notes: "Industrial/concrete grease peer to Oil Eater—dilute per label; not default for cooktop polish or stone.",
    amazonUrl: "https://www.amazon.com/dp/B000BQK8Y2",
  },
  {
    id: "therapy_stainless_steel_cleaner_polish",
    slug: "therapy-stainless-steel-cleaner-polish",
    name: "Therapy Stainless Steel Cleaner & Polish",
    brand: "Therapy",
    category: "stainless polish",
    chemicalClass: "stainless_polish",
    intent: "clean",
    surfaces: ["finished stainless", "stainless steel appliances", "stainless steel", "finished appliances", "appliances"],
    problems: ["fingerprints", "surface haze", "smudge marks", "light film", "streaking", "dullness"],
    notes: "Weiman-class stainless appearance peer—not mineral, rust, or baked carbon chemistry.",
    amazonUrl: "https://www.amazon.com/dp/B00L2P0KNO",
  },
  {
    id: "mold_armor_rapid_clean_remediation",
    slug: "mold-armor-rapid-clean-remediation",
    name: "Mold Armor Rapid Clean Remediation",
    brand: "Mold Armor",
    category: "mold remediation spray",
    chemicalClass: "mold_control",
    intent: "clean",
    surfaces: ["tile", "shower glass", "porcelain", "ceramic", "grout", "drywall", "bathtubs"],
    problems: ["mold staining", "mildew growth", "mold growth", "mildew stains", "biofilm"],
    notes: "Stronger mold/mildew remediation tone vs Concrobium control—still not pet urine, laundry refresh, or descaling.",
    amazonUrl: "https://www.amazon.com/dp/B001DWD0BQ",
  },
  {
    id: "scrubbing_bubbles_daily_shower_cleaner",
    slug: "scrubbing-bubbles-daily-shower-cleaner",
    name: "Scrubbing Bubbles Daily Shower Cleaner",
    brand: "Scrubbing Bubbles",
    category: "shower maintenance spray",
    chemicalClass: "surfactant",
    intent: "maintain",
    surfaces: ["shower glass", "tile", "porcelain", "ceramic", "chrome"],
    problems: ["preventive maintenance", "soap scum", "light film"],
    notes: "Fourth daily shower maintainer—soap-scum-adjacent; still weak on hard mineral restore.",
    amazonUrl: "https://www.amazon.com/dp/B016WFFGCI",
  },
  {
    id: "pledge_everyday_clean_multisurface",
    slug: "pledge-everyday-clean-multisurface",
    name: "Pledge Everyday Clean Multisurface",
    brand: "Pledge",
    category: "multisurface dust cleaner",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["cabinet fronts", "cabinets", "finished wood", "sealed wood", "laminate", "painted trim"],
    problems: ["light dust", "light film", "dust buildup", "smudge marks"],
    notes: "Second Pledge-style cabinet/dust lane—Murphy/Method peers for light film, not floor oil programs.",
    amazonUrl: "https://www.amazon.com/dp/B08N5WRWNW",
  },
  {
    id: "krud_kutter_kitchen_degreaser",
    slug: "krud-kutter-kitchen-degreaser",
    name: "Krud Kutter Kitchen Degreaser",
    brand: "Krud Kutter",
    category: "kitchen degreaser spray",
    chemicalClass: "alkaline",
    intent: "clean",
    surfaces: ["cooktops", "range hoods", "stainless steel appliances", "stainless steel"],
    problems: ["kitchen grease film", "greasy film", "grease buildup", "food residue", "cooked-on grease", "light film"],
    notes: "Third cooktop/hood specialist—filtered off true oven/grill baked-on; not a broad industrial default.",
    amazonUrl: "https://www.amazon.com/dp/B07HJH5B9J",
  },
  {
    id: "febreze_fabric_refresher_antimicrobial",
    slug: "febreze-fabric-refresher-antimicrobial",
    name: "Febreze Fabric Refresher Antimicrobial",
    brand: "Febreze",
    category: "fabric odor refresher",
    chemicalClass: "surfactant",
    intent: "clean",
    surfaces: ["fabric", "fabrics", "bedding", "towels", "upholstery", "laundry", "delicates"],
    problems: ["musty odor", "laundry odor", "odor retention", "pet odor"],
    notes: "Light fabric refresh/musty lane—verify label; not a laundry-cycle sanitizer substitute.",
    amazonUrl: "https://www.amazon.com/dp/B003P1QBCG",
  },
  {
    id: "goo_gone_spray_gel",
    slug: "goo-gone-spray-gel",
    name: "Goo Gone Spray Gel",
    brand: "Goo Gone",
    category: "adhesive remover (gel)",
    chemicalClass: "solvent_blend",
    intent: "remove_residue",
    surfaces: ["plastic", "laminate", "painted surfaces", "glass", "vertical surfaces"],
    problems: ["light adhesive residue", "sticky residue", "adhesive residue"],
    notes: "Gel format for vertical/light tacky soil—spot-test finishes; heavy gum still 3M/Goof Off territory.",
    amazonUrl: "https://www.amazon.com/dp/B004W2UBI8",
  },
  {
    id: "zero_odor_eliminator_spray",
    slug: "zero-odor-eliminator-spray",
    name: "Zero Odor Eliminator Spray",
    brand: "Zero Odor",
    category: "odor neutralizer spray",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: [
      "fabric",
      "fabrics",
      "upholstery",
      "carpet",
      "laundry",
      "bedding",
      "towels",
      "general household surfaces",
    ],
    problems: ["musty odor", "odor retention", "pet odor"],
    notes: "Neutralization-forward odor peer—musty/soft-surface lane vs fragrance-only refresh; not disinfect or degrease.",
    amazonUrl: "https://www.amazon.com/dp/B000JF9CF6",
  },
  {
    id: "fresh_wave_odor_removing_spray",
    slug: "fresh-wave-odor-removing-spray",
    name: "Fresh Wave Odor Removing Spray",
    brand: "Fresh Wave",
    category: "plant-based odor spray",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["fabric", "fabrics", "upholstery", "carpet", "laundry", "bedding", "towels", "garbage cans"],
    problems: ["musty odor", "odor retention", "pet odor", "laundry odor"],
    notes: "Soft-surface deodorizing peer—expands odor branch beyond enzymes and Febreze; not sanitizer chemistry.",
    amazonUrl: "https://www.amazon.com/dp/B001B6SRB8",
  },
  {
    id: "cerama_bryte_cooktop_cleaner",
    slug: "cerama-bryte-cooktop-cleaner",
    name: "Cerama Bryte Cooktop Cleaner",
    brand: "Cerama Bryte",
    category: "cooktop surface cleaner",
    chemicalClass: "neutral",
    intent: "clean",
    surfaces: ["cooktops", "glass"],
    problems: ["smudge marks", "light film", "light dust", "streaking", "product residue"],
    notes: "Precision glass/ceramic cooktop cosmetic cleaner—heavy degreasers and oven SKUs penalized on light film/smudge.",
    amazonUrl: "https://www.amazon.com/dp/B001TI570A",
  },
  {
    id: "sprayway_stainless_steel_cleaner",
    slug: "sprayway-stainless-steel-cleaner",
    name: "Sprayway Stainless Steel Cleaner",
    brand: "Sprayway",
    category: "stainless steel cleaner",
    chemicalClass: "stainless_polish",
    intent: "clean",
    surfaces: ["stainless steel", "stainless steel appliances", "finished stainless", "finished appliances", "appliances", "chrome"],
    problems: ["fingerprints", "surface haze", "smudge marks", "light film", "streaking", "dullness"],
    notes: "Third stainless_polish cluster member—appearance lane; weak on grease scale and mineral restore.",
    amazonUrl: "https://www.amazon.com/dp/B001F0QKZU",
  },
];

export const PRODUCTS: ProductSeed[] = PRODUCTS_RAW.map((seed) => {
  const amazonImport = getAmazonCatalogImportBySlug(seed.slug);

  const mergedAmazonUrl =
    amazonImport?.amazonUrl ||
    seed.amazonUrl ||
    PURCHASE_AMAZON_FALLBACK[seed.slug] ||
    undefined;

  const mergedAmazonAffiliateUrl =
    amazonImport?.amazonAffiliateUrl || seed.amazonAffiliateUrl || undefined;

  const mergedBrand = amazonImport?.brand || seed.brand || undefined;

  // Normalized import (via registry) wins for imagery; seed fills gaps.
  const mergedPrimaryImageUrl =
    amazonImport?.primaryImageUrl || seed.primaryImageUrl || undefined;

  const mergedImageUrls =
    amazonImport?.imageUrls && amazonImport.imageUrls.length > 0
      ? amazonImport.imageUrls
      : seed.imageUrls || [];

  const mergedBuyLabel =
    amazonImport?.buyLabel || seed.buyLabel || "Buy on Amazon";

  const mergedPurchaseAvailable =
    amazonImport?.isPurchaseAvailable ??
    seed.isPurchaseAvailable ??
    PURCHASE_READY_SEED_SLUGS.has(seed.slug);

  const normalizedImageUrls = mergedImageUrls.filter(Boolean);

  return withAmazonDefaults({
    ...seed,
    brand: mergedBrand ?? seed.brand,
    amazonUrl: mergedAmazonUrl ?? "",
    amazonAffiliateUrl: mergedAmazonAffiliateUrl ?? "",
    primaryImageUrl: mergedPrimaryImageUrl,
    imageUrls: normalizedImageUrls,
    buyLabel: mergedBuyLabel,
    isPurchaseAvailable: mergedPurchaseAvailable,
  });
});
