import type { EvidenceRecord } from "./evidenceTypes";

/** Evidence added for encyclopedia seed-batch-011 (painted cluster + utility soap/sticky/burnt/scuff/odor + glass bio + laminate oil/burnt/scuff). */
export const BATCH_011_EVIDENCE: EvidenceRecord[] = [
  {
    surface: "painted surfaces",
    problem: "oil stains",
    soilClass: "grease",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["solvent"],
    products: [
      {
        name: "Mild alkaline cleaner for washable paint",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Emulsifies cooking and skin oils on intact paint films.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Kitchen plumes and hand contact deposit oils on satin or semi-gloss cabinet and trim paint.",
    whyItWorks: "Surfactants solubilize triglyceride films so they release into the cloth instead of smearing.",
    mistakes: ["Strong solvents that soften alkyd or latex."],
    benchmarks: ["Sheen stays uniform after dry-down."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "food residue",
    soilClass: "organic",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "pH-neutral wall cleaner",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Lifts dried food films without etching or dulling paint.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Splatter polymerizes on vertical paint near prep zones.",
    whyItWorks: "Neutral surfactants reduce adhesion of carbohydrate and protein films.",
    mistakes: ["Over-wetting seams and outlets."],
    benchmarks: ["Tack disappears when judged after full dry."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "protein residue",
    soilClass: "organic",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Neutral cleaner with light enzymatic option if labeled",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Breaks protein films that resist plain water on paint.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Egg and dairy denature into tacky films on cabinet faces.",
    whyItWorks: "Protease or surfactant systems cleave or lift protein without aggressive pH.",
    mistakes: ["Scrubbing through sheen on soft paint."],
    benchmarks: ["Protein drag reduces after rinse cycles."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "rust stains",
    soilClass: "mineral",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Neutral cleaner plus spot poultice if system allows paint",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Differentiates topical iron staining from paint failure.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Moisture wicking from fasteners can leave orange films on paint.",
    whyItWorks: "Controlled chemistry avoids random acid that damages color.",
    mistakes: ["Spreading strong acid across broad wall areas."],
    benchmarks: ["Stain feathers only when chemistry matches the stain type."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "tannin stains",
    soilClass: "organic",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Alkaline wall cleaner; oxygen system only if paint label allows",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Attacks polyphenol films from beverages on paint.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Coffee and tea overspray leaves ringed color on light paint.",
    whyItWorks: "Alkaline surfactants lift many tannin films before repainting.",
    mistakes: ["Bleach on unknown pigments without testing."],
    benchmarks: ["Ring lightens when film not absorbed into substrate."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "bacteria buildup",
    soilClass: "biofilm",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "EPA-registered disinfectant cleaner for painted surfaces when labeled",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Removes soil so disinfectant dwell is meaningful.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Humid baths sustain bacterial films on painted drywall and trim.",
    whyItWorks: "Clean-then-disinfect sequencing matches health guidance.",
    mistakes: ["Spraying disinfectant through heavy grease."],
    benchmarks: ["Slippery biofilm sheen gone after dry."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "etching",
    soilClass: "damage",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic","alkaline"],
    products: [
      {
        name: "Neutral cleaner for assessment only",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "True etch is coating damage; cleaning cannot rebuild film.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Acid splashes or aggressive cleaners alter paint gloss locally.",
    whyItWorks: "Neutral care prevents spread; recoating fixes real etch.",
    mistakes: ["More acid trying to even gloss."],
    benchmarks: ["No further dulling after gentle neutral wipe."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "oxidation",
    soilClass: "damage",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Neutral cleaner for film-only cases",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Many dark marks are soil; oxidation of metal trim differs.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Heat and UV oxidize alkyd films unevenly near fixtures.",
    whyItWorks: "Neutral removal confirms whether mark is removable film.",
    mistakes: ["Assuming all darkening is dirt."],
    benchmarks: ["Uniformity improves only when soil was the driver."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "corrosion",
    soilClass: "damage",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic","alkaline"],
    products: [
      {
        name: "Neutral paint-safe wipe; service metal separately",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Paint care is protective while corroded hardware is addressed.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Electrolyte films accelerate fixture corrosion that stains adjacent paint.",
    whyItWorks: "Isolation prevents metal chemistry from attacking paint.",
    mistakes: ["Spraying metal acids across painted saddles."],
    benchmarks: ["Paint edge stays stable after rinsing splashes."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "tarnish",
    soilClass: "damage",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Neutral wipe; mask paint when polishing adjacent metal",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Tarnish calls usually involve metal on painted surrounds.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Humidity and cleaner residues plate oxides on brass near painted jambs.",
    whyItWorks: "Barrier keeps metal chemistry off latex.",
    mistakes: ["Dragging silver dip across painted returns."],
    benchmarks: ["Paint unchanged; metal treated per metal label."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "painted surfaces",
    problem: "heat damage",
    soilClass: "damage",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic","alkaline"],
    products: [
      {
        name: "Neutral cleaner for soot-like residue assessment",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Heat can alter resin; cleaning only helps removable char.",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Cooking heat and vent gaps deposit pyrolyzed film on nearby paint.",
    whyItWorks: "Gentle removal avoids embedding soot.",
    mistakes: ["Aggressive scrub on softened paint."],
    benchmarks: ["Loose soot may reduce; gloss change may persist."],
    professionalInsights: ["Test hidden area on cabinets before full wall passes."],
    sources: ["paint manufacturer maintenance PDFs"],
  },
  {
    surface: "glass",
    problem: "burnt residue",
    soilClass: "grease",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["solvent"],
    products: [
      {
        name: "Alkaline glass cleaner with degreasing surfactants",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Softens carbonized film on shower glass",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Cooking plumes plate carbon on doors and panels",
    whyItWorks: "Alkaline surfactants emulsify char-prone grease",
    mistakes: ["Metal scrapers on coated glass"],
    benchmarks: ["Carbon lifts in layers when dwell is respected"],
    professionalInsights: ["Keep acid off adjacent stone thresholds"],
    sources: ["glass restoration field notes"],
  },
  {
    surface: "glass",
    problem: "scuff marks",
    soilClass: "damage",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "pH-neutral glass cleaner",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Lifts transfer scuffs above the glass surface",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Rubber and plastic contact leaves films on doors",
    whyItWorks: "Neutral surfactants remove transfer without etching",
    mistakes: ["Dry dusting before wet which grinds grit"],
    benchmarks: ["Scuffs lighten without new swirl pattern"],
    professionalInsights: ["Do not confuse etch fog with scuff transfer"],
    sources: ["professional glass cleaning basics"],
  },
  {
    surface: "glass",
    problem: "mold growth",
    soilClass: "biofilm",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "EPA-registered bath cleaner rated for glass",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Removes organic film before disinfectant dwell",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Humid enclosures grow mold on glass corners",
    whyItWorks: "Mechanical plus labeled kill step reduces biomass",
    mistakes: ["Bleach-only without soil removal"],
    benchmarks: ["Visible growth clears at grout-to-glass transitions"],
    professionalInsights: ["Ventilation matters as much as chemistry"],
    sources: ["EPA label use-site guidance"],
  },
  {
    surface: "glass",
    problem: "mildew stains",
    soilClass: "biofilm",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Alkaline mildew treatment with surfactants",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Targets pigmented mildew film on glass",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Body soils feed mildew at silicone corners",
    whyItWorks: "Surfactants carry pigment; follow label dwell",
    mistakes: ["Sealing over stained silicone without cleaning"],
    benchmarks: ["Stain lightens across multiple dry cycles"],
    professionalInsights: ["Replace failed silicone if growth returns"],
    sources: ["manufacturer mildew cleaner use sites"],
  },
  {
    surface: "laminate",
    problem: "burnt residue",
    soilClass: "grease",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["solvent"],
    products: [
      {
        name: "Mild alkaline degreaser for laminate",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Softens carbonized splash on vertical laminate",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Cooking mist carbonizes near cooktops and edges",
    whyItWorks: "Alkaline chemistry targets organic char phase",
    mistakes: ["Flooding melamine seams"],
    benchmarks: ["Bonded film softens with controlled dwell"],
    professionalInsights: ["Spot-test decorative laminate first"],
    sources: ["laminate manufacturer care bulletins"],
  },
  {
    surface: "laminate",
    problem: "scuff marks",
    soilClass: "damage",
    recommendedChemistry: "neutral",
    avoidChemistry: ["solvent"],
    products: [
      {
        name: "pH-neutral laminate cleaner",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Removes transfer scuff without swelling edges",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Chair backs and tools leave melamine scuffs",
    whyItWorks: "Neutral cleaning avoids solvent swelling",
    mistakes: ["Abrasive pads without testing"],
    benchmarks: ["Scuff fades without joint swelling"],
    professionalInsights: ["Heat damage does not clean away like scuff"],
    sources: ["laminate field maintenance notes"],
  },
  {
    surface: "laminate",
    problem: "oil stains",
    soilClass: "grease",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["solvent"],
    products: [
      {
        name: "Alkaline surfactant cleaner safe for laminate",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Emulsifies cooking oils on counters and backsplashes",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Oils wick to seams and edge banding",
    whyItWorks: "Surfactants lift oils before polymerization",
    mistakes: ["Acetone flooding on printed surfaces"],
    benchmarks: ["Oil sheen gone at dry hand test"],
    professionalInsights: ["Keep liquid out of seams"],
    sources: ["kitchen laminate care summaries"],
  },
  {
    surface: "countertops",
    problem: "soap residue",
    soilClass: "residue",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Alkaline multi-surface cleaner rated for the assembly",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Breaks soap–mineral complex on mixed tops",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Hard water plus surfactants cure scum rings",
    whyItWorks: "Alkaline cut combined with rinse clears film",
    mistakes: ["Acid guessing on unknown stone inserts"],
    benchmarks: ["Water sheets more evenly after rinse"],
    professionalInsights: ["Identify stone zones before acid anywhere"],
    sources: ["kitchen multi-material counter care"],
  },
  {
    surface: "countertops",
    problem: "sticky residue",
    soilClass: "residue",
    recommendedChemistry: "neutral",
    avoidChemistry: ["solvent"],
    products: [
      {
        name: "pH-neutral adhesive-release cleaner (test)",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Lifts tape and sugar films on tolerant tops",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Labels and spills tack on quartz and laminate seams",
    whyItWorks: "Neutral systems solubilize polar tack without etch",
    mistakes: ["Soaking open seams overnight"],
    benchmarks: ["Tack gone without gloss patch"],
    professionalInsights: ["Separate workflows for stone vs synthetic"],
    sources: ["countertop manufacturer care PDFs"],
  },
  {
    surface: "countertops",
    problem: "burnt residue",
    soilClass: "grease",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["solvent"],
    products: [
      {
        name: "Alkaline degreaser for tolerant counter materials",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Softens cooked-on film on non-porous tops",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Hot pans splatter carbonized grease across islands",
    whyItWorks: "Alkaline dwell emulsifies organic char",
    mistakes: ["Scraping polished stone blindly"],
    benchmarks: ["Film softens in layers with dwell"],
    professionalInsights: ["Confirm substrate before aggressive pads"],
    sources: ["professional cooktop-adjacent counter workflows"],
  },
  {
    surface: "countertops",
    problem: "scuff marks",
    soilClass: "damage",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Neutral cleaner for scuff transfer",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Distinguishes transfer from scratch in topcoat",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Tools and ceramics leave scuff films",
    whyItWorks: "Neutral lift reduces transfer without frost",
    mistakes: ["Powder abrasives on gloss quartz"],
    benchmarks: ["Uniform sheen after gentle passes"],
    professionalInsights: ["Deep scratches need repair not chemistry"],
    sources: ["solid surface care references"],
  },
  {
    surface: "countertops",
    problem: "odor retention",
    soilClass: "organic",
    recommendedChemistry: "alkaline",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Alkaline cleaner with odor-counteractant surfactants",
        chemistry: "alkaline",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Removes organic films that hold odor on porous seams",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Spills into seams and grout lines rehydrate smells",
    whyItWorks: "Cleaning opens surfaces so ventilation works",
    mistakes: ["Masking with fragrance oils only"],
    benchmarks: ["Odor drops after thorough rinse and dry"],
    professionalInsights: ["Fix moisture in seams if smell returns"],
    sources: ["kitchen odor source triage notes"],
  },
  {
    surface: "toilets",
    problem: "soap residue",
    soilClass: "residue",
    recommendedChemistry: "acidic",
    avoidChemistry: ["alkaline"],
    products: [
      {
        name: "Acidic toilet cleaner safe for vitreous china",
        chemistry: "acidic",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Dissolves soap–mineral complex above waterline",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Hard water binds surfactants to china curves",
    whyItWorks: "Acid frees mineral backbone of scum",
    mistakes: ["Using bowl acid on decorative metal without rinse"],
    benchmarks: ["China brightens where scum was bonded"],
    professionalInsights: ["Separate exterior chrome care"],
    sources: ["fixture manufacturer cleaning guides"],
  },
  {
    surface: "toilets",
    problem: "sticky residue",
    soilClass: "residue",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "Neutral bathroom cleaner for china and seat zones",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Removes adhesive and wax films on exterior china",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Aerosol products plate tacky films on bases",
    whyItWorks: "Neutral surfactants lift polar residues",
    mistakes: ["Same rag from bowl acid to exterior without rinse"],
    benchmarks: ["Base feels clean-dry after buff"],
    professionalInsights: ["Wear gloves; change cloths often"],
    sources: ["restroom finishing field notes"],
  },
  {
    surface: "mirrors",
    problem: "soap residue",
    soilClass: "residue",
    recommendedChemistry: "acidic",
    avoidChemistry: ["alkaline"],
    products: [
      {
        name: "Acidic glass cleaner safe for mirror face (frame test)",
        chemistry: "acidic",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Attacks soap–mineral haze on reflective glass",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Toothpaste and shave products plate scum on lower thirds",
    whyItWorks: "Acid frees surfactant–mineral complexes",
    mistakes: ["Soaking mirror backing edges"],
    benchmarks: ["Reflection clears where coating intact"],
    professionalInsights: ["Tape vulnerable backing seams"],
    sources: ["glass restoration trade practices"],
  },
  {
    surface: "mirrors",
    problem: "sticky residue",
    soilClass: "residue",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "pH-neutral mirror cleaner",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Lifts adhesives without attacking backing adhesives",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Labels and cosmetics leave polar films",
    whyItWorks: "Neutral surfactants carry tack off the face",
    mistakes: ["Ammonia when manufacturer forbids it"],
    benchmarks: ["Drag test clean after dry buff"],
    professionalInsights: ["Use two lint-low cloths"],
    sources: ["professional glass cleaning basics"],
  },
  {
    surface: "vinyl",
    problem: "soap residue",
    soilClass: "residue",
    recommendedChemistry: "neutral",
    avoidChemistry: ["acidic"],
    products: [
      {
        name: "pH-neutral vinyl floor cleaner",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Rinses surfactant films that attract soil on embossed vinyl",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Mop buckets redeposit soap in texture",
    whyItWorks: "Neutral chemistry rinses clean for even dry-down",
    mistakes: ["High-pH stripper on residential wear layer"],
    benchmarks: ["No tack after dry-down"],
    professionalInsights: ["Change rinse water at doorways"],
    sources: ["resilient flooring care guides"],
  },
  {
    surface: "vinyl",
    problem: "sticky residue",
    soilClass: "residue",
    recommendedChemistry: "neutral",
    avoidChemistry: ["solvent"],
    products: [
      {
        name: "Neutral cleaner for spot tack on vinyl (test)",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Removes adhesive and wax transfer without solvent shock",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Tape and stickers leave grip on plank embossing",
    whyItWorks: "Controlled neutral lift limits plasticizer stress",
    mistakes: ["Pouring aggressive solvents broadly"],
    benchmarks: ["Spot tack gone without gloss loss"],
    professionalInsights: ["Test hidden plank first"],
    sources: ["resilient flooring warranty chemistry notes"],
  },
  {
    surface: "general household surfaces",
    problem: "sticky residue",
    soilClass: "residue",
    recommendedChemistry: "neutral",
    avoidChemistry: ["solvent"],
    products: [
      {
        name: "pH-neutral utility cleaner",
        chemistry: "neutral",
        surfaces: ["painted surfaces"],
        avoids: ["flat paint without prior test"],
        reason: "Cuts sugar and adhesive films on bins and utility plastics",
      },
    ],
    method: {
      tools: ["soft sponge", "microfiber"],
      dwell: "Brief; small sections",
      agitation: "Light; protect sheen",
      rinse: "Damp clear water",
      dry: "Pat dry",
    },
    whyItHappens: "Garage and laundry plastics collect label goo",
    whyItWorks: "Surfactants solubilize polar films safely",
    mistakes: ["Using metal scrapers on thin plastic"],
    benchmarks: ["Drag-free feel after dry-down"],
    professionalInsights: ["Sort plastics before solvent attempts"],
    sources: ["utility plastic maintenance summaries"],
  },
];
