import type { ChemistryClass, CleaningMethod, CleaningProduct, EvidenceRecord, SoilClass } from "./evidenceTypes";

/**
 * Batch 017A — evidence-only closure for the final 33 canonical pairs left after batch-016 seed trim.
 * No seed/generate: live gap-kill uses separate batch-017 seeds from corpus-gap lines.
 */
const BATH_TRIPLE = ["toilets", "mirrors", "vinyl"] as const;

function mapTriple(
  problem: string,
  soilClass: SoilClass,
  recommendedChemistry: ChemistryClass,
  avoidChemistry: ChemistryClass[],
  productBase: Omit<CleaningProduct, "surfaces">,
  method: CleaningMethod,
  whyItHappens: string,
  whyItWorks: string,
  mistakes: string[],
  benchmark: string,
  professionalInsight: string,
  sources: string[],
): EvidenceRecord[] {
  return BATH_TRIPLE.map((surface) => ({
    surface,
    problem,
    soilClass,
    recommendedChemistry,
    avoidChemistry,
    products: [{ ...productBase, surfaces: [surface] }],
    method,
    whyItHappens,
    whyItWorks,
    mistakes,
    benchmarks: [benchmark],
    professionalInsights: [professionalInsight],
    sources,
  }));
}

function ct017a(
  problem: string,
  soilClass: SoilClass,
  recommendedChemistry: ChemistryClass,
  avoidChemistry: ChemistryClass[],
  product: CleaningProduct,
  method: CleaningMethod,
  whyItHappens: string,
  whyItWorks: string,
  mistakes: string[],
  benchmark: string,
  professionalInsight: string,
  sources: string[],
): EvidenceRecord {
  return {
    surface: "countertops",
    problem,
    soilClass,
    recommendedChemistry,
    avoidChemistry,
    products: [product],
    method,
    whyItHappens,
    whyItWorks,
    mistakes,
    benchmarks: [benchmark],
    professionalInsights: [professionalInsight],
    sources,
  };
}

function gh017a(
  problem: string,
  soilClass: SoilClass,
  recommendedChemistry: ChemistryClass,
  avoidChemistry: ChemistryClass[],
  product: CleaningProduct,
  method: CleaningMethod,
  whyItHappens: string,
  whyItWorks: string,
  mistakes: string[],
  benchmark: string,
  professionalInsight: string,
  sources: string[],
): EvidenceRecord {
  return {
    surface: "general household surfaces",
    problem,
    soilClass,
    recommendedChemistry,
    avoidChemistry,
    products: [product],
    method,
    whyItHappens,
    whyItWorks,
    mistakes,
    benchmarks: [benchmark],
    professionalInsights: [professionalInsight],
    sources,
  };
}

const M_CT: CleaningMethod = {
  tools: ["microfiber", "sponge", "small brush for seams and caulk"],
  dwell: "Brief; work in sections so chemistry does not dry on the field",
  agitation: "Even light pressure; identify stone vs synthetic zones first",
  rinse: "Clear damp wipes; repeat until drag disappears",
  dry: "Towel buff; judge in cross-light when fully dry",
};

const M_GH: CleaningMethod = {
  tools: ["microfiber", "brush for ribs", "hose or tub rinse where practical"],
  dwell: "Short unless label extends for utility plastics",
  agitation: "Scrub interior patterns and corners",
  rinse: "Volume outdoor or utility rinse when possible",
  dry: "Invert, towel, or air dry before re-lidding",
};

const TRIPLE_017A: EvidenceRecord[] = [
  ...mapTriple(
    "dust buildup",
    "residue",
    "neutral",
    ["acidic"],
    {
      name: "Dry microfiber dusting followed by neutral damp wipe for bathroom hard surfaces",
      chemistry: "neutral",
      avoids: ["oily dusters that build film", "wet-only passes that mud particulate"],
      reason: "Dry capture first prevents mud streaks on vitreous china, mirror glass, and vinyl wear layers.",
    },
    {
      tools: ["microfiber duster", "second dry cloth", "soft detailing brush"],
      dwell: "N/A for dry phase; damp phase brief only",
      agitation: "Top-down linear dusting then even damp wipes",
      rinse: "Barely damp rinse if cleaner residue drags",
      dry: "Immediate buff on porcelain, mirror, and vinyl fields",
    },
    "Bathroom static, skin flakes, and cosmetic overspray make dust cling to toilet porcelains, mirror glass, and embossed vinyl so it smears when wet-wiped first.",
    "Dry microfiber removes bulk lint before a short neutral damp pass lifts remaining film without grinding grit into glaze, silvering edges, or wear texture.",
    [
      "Wet-mopping porcelain before dry dusting.",
      "Silicone sprays on mirrors that attract more dust.",
      "Beater bars or stiff brooms that scuff vinyl embossing.",
    ],
    "Surfaces should read cleaner in raking light after dry-then-damp sequence.",
    "Change gray mop water; streaks often mean soil reload not worn finish.",
    ["dust control housekeeping references"],
  ),
  ...mapTriple(
    "mold growth",
    "biofilm",
    "alkaline",
    ["acidic"],
    {
      name: "EPA-registered disinfectant cleaner for bathroom hard surfaces after preclean",
      chemistry: "alkaline",
      avoids: ["painting over growth", "bleach-only without soil removal"],
      reason: "Mechanical preclean plus labeled wet time reduces surface biomass on non-porous fields when moisture is managed.",
    },
    {
      tools: ["nylon brush", "PPE", "microfiber"],
      dwell: "Preclean then full disinfectant wet time per label",
      agitation: "Corners, hinges, and cove bases first",
      rinse: "Rinse before shower reuse if label requires",
      dry: "Ventilate aggressively; fix chronic condensation",
    },
    "Chronic condensation, tank sweating, slow-dry mirror perimeters, and wet mopping sustain mold on porcelain, glass edges, and bath-adjacent vinyl.",
    "Soil removal followed by disinfectant at proper contact time addresses visible growth when exhaust CFM and leak sources are corrected.",
    ["Sealing over moldy caulk.", "Ignoring fan capacity or dishwasher-side leaks.", "Acid same day without thorough rinse between steps."],
    "Visible growth should clear when humidity drops; recurrence signals an active moisture path.",
    "Silvering creep at mirror edges often tracks wall moisture—not stronger bottle chemistry alone.",
    ["EPA label guidance", "IICRC mold overview context"],
  ),
  ...mapTriple(
    "mildew stains",
    "biofilm",
    "alkaline",
    ["acidic"],
    {
      name: "Alkaline mildew-treatment cleaner with surfactants for bath and floor vinyl",
      chemistry: "alkaline",
      avoids: ["acid same day without rinse between", "short dwell that leaves pigment"],
      reason: "Surfactants lift pigmented mildew film while ventilation stops immediate return on hard surfaces.",
    },
    {
      tools: ["soft brush", "microfiber"],
      dwell: "Per label for stain lift",
      agitation: "Perimeter grout, caulk, and cove lines before field",
      rinse: "Complete rinse",
      dry: "Dry within hours; increase airflow",
    },
    "Humid dishwashing and baths deposit mildew pigments on porcelain bases, mirror corners, and vinyl texture where drying is slowest.",
    "Alkaline surfactant packages remove surface hyphae staining when joints can dry between cycles.",
    ["Wax or oil that traps moisture.", "Soaking paper gaskets or unsealed wood adjacent to vinyl.", "Bleach cocktails with acid."],
    "Pigment should lighten across dry evaluations when film has not penetrated caulk body.",
    "Pink or black stain through silicone usually needs new caulk, not only surface wiping.",
    ["mildew cleaner manufacturer labels"],
  ),
];

const COUNTERTOP_017A: EvidenceRecord[] = [
  ct017a(
    "dust buildup",
    "residue",
    "neutral",
    ["acidic"],
    {
      name: "Dry microfiber then neutral stone-or-synthetic safe dusting spray if needed",
      chemistry: "neutral",
      surfaces: ["countertops", "quartz", "laminate counters", "sealed stone"],
      avoids: ["silicone-heavy dust sprays near food prep"],
      reason: "Horizontal tops show dust in raking light; dry removal prevents mud on mixed quartz, laminate, and sealed stone.",
    },
    {
      tools: ["microfiber", "small brush for backsplash ledge"],
      dwell: "N/A",
      agitation: "Linear wipes top-down",
      rinse: "Barely damp if needed",
      dry: "Buff",
    },
    "Skin flakes, lint, and pollen cling to static-charged horizontal counters and settle into seams on busy kitchens.",
    "Dry microfiber captures dust before damp work adapts safely across quartz, laminate, and sealed stone in one routine.",
    ["Wet-only first pass that streaks dust into seams.", "Same cloth from bath to kitchen without laundering."],
    "Surface should read cleaner in cross-light after dry-then-damp sequence.",
    "Dust can hide etch or resin wear—identify material before assuming soil-only dullness.",
    ["multi-material countertop housekeeping notes"],
  ),
  ct017a(
    "oil stains",
    "grease",
    "alkaline",
    ["acidic"],
    {
      name: "Mild alkaline degreaser labeled for the installed countertop type",
      chemistry: "alkaline",
      surfaces: ["countertops", "quartz countertops", "laminate counters"],
      avoids: ["unknown natural stone without test", "chlorine prolonged dwell"],
      reason: "Kitchen oils emulsify under alkaline surfactants on tolerant synthetics and sealed tops after spot test.",
    },
    M_CT,
    "Cooking oils and hand films plate into texture and seams on prep zones and islands.",
    "Alkaline cleaner cuts grease when label matches quartz, laminate, or sealed stone after controlled dwell.",
    ["Guessing every top is quartz.", "Pooling degreaser into open laminate seams.", "Acid on marble saddles without protection."],
    "Oil sheen should drop after dry inspection.",
    "Dark granites often tolerate different dwell than white quartz—document test spots.",
    ["kitchen counter degreasing primers"],
  ),
  ct017a(
    "food residue",
    "organic",
    "neutral",
    ["acidic"],
    {
      name: "Neutral pH countertop cleaner",
      chemistry: "neutral",
      surfaces: ["countertops"],
      avoids: ["bleach on protein without preclean"],
      reason: "Neutral surfactants lift carbohydrates and fats without guessing acid tolerance on mixed assemblies.",
    },
    M_CT,
    "Dried jam, starch, and drink films bond to horizontal tops near prep and sink splash lines.",
    "Neutral detergency releases polar food soils across mixed countertop families safely.",
    ["Gritty pads on gloss quartz.", "Letting juice dry into open seams."],
    "Tack should clear within one or two light cycles.",
    "Remove crumbs before wetting to avoid scratch cycles from trapped grit.",
    ["countertop daily care guides"],
  ),
  ct017a(
    "protein residue",
    "organic",
    "alkaline",
    ["acidic"],
    {
      name: "Cool alkaline or labeled enzyme cleaner for countertops after material check",
      chemistry: "alkaline",
      surfaces: ["countertops", "stainless steel", "quartz"],
      avoids: ["hot water on some resin tops"],
      reason: "Protein films from egg and dairy release with controlled alkaline or enzyme steps on non-porous tops.",
    },
    M_CT,
    "Breakfast prep and pet dishes leave denatured protein that tacks on cool mornings and near sink zones.",
    "Cool alkaline surfactancy breaks protein adhesion when dwell stays short and rinse is complete.",
    ["Heat setting egg on adjacent backsplash.", "Acid chasing haze on marble neighbors without isolation."],
    "Protein drag should fall after thorough rinse and dry.",
    "Segment raw-meat zones to avoid cross-wipe contamination patterns.",
    ["food-prep surface cleaning notes"],
  ),
  ct017a(
    "rust stains",
    "mineral",
    "acidic",
    ["alkaline"],
    {
      name: "Acidic rust spot gel tested on hidden area per countertop type",
      chemistry: "acidic",
      surfaces: ["countertops", "quartz", "laminate counters"],
      avoids: ["marble without professional guidance", "bleach mixes"],
      reason: "Targeted acid dissolves iron oxide on tolerant tops when stone neighbors are masked or avoided.",
    },
    {
      tools: ["cotton swab", "mask for stone", "timer"],
      dwell: "Spot; shortest effective",
      agitation: "Minimal; let chemistry work",
      rinse: "Neutralizing or flood rinse per label",
      dry: "Inspect dry color",
    },
    "Can rings and wet cast iron leave iron oxides on light quartz and laminate fields.",
    "Tested acidic contact reduces rust transfer without sheet-treating the entire kitchen.",
    ["Acid on unsealed stone.", "Letting acid dry on grout or caulk lines."],
    "Rust tone should step down in controlled passes.",
    "Active pan rust needs reseasoning—not only counter spot work.",
    ["rust spot treatment labels"],
  ),
  ct017a(
    "tannin stains",
    "organic",
    "neutral",
    ["acidic"],
    {
      name: "Oxygen bleach or peroxide system tested on hidden countertop area",
      chemistry: "neutral",
      surfaces: ["countertops"],
      avoids: ["chlorine mixed with acid"],
      reason: "Controlled oxidation can lighten organic browns on sealed synthetics when manufacturer allows.",
    },
    M_CT,
    "Coffee and tea wick to seams and leave brown chromophores on light tops and near sink glides.",
    "Peroxide-class steps can fade removable tannin films after thorough preclean and spot testing.",
    ["Over-dwell whitening epoxy seams.", "Using wood-only brighteners on plastic laminate."],
    "Brown should lighten across evaluations when stain is topical film.",
    "If color wicks under joint, mechanical joint repair may be required.",
    ["oxygen cleaner countertop cautions"],
  ),
  ct017a(
    "mold growth",
    "biofilm",
    "alkaline",
    ["acidic"],
    {
      name: "EPA-registered disinfectant after preclean on non-porous countertops",
      chemistry: "alkaline",
      surfaces: ["countertops"],
      avoids: ["sealing over active growth"],
      reason: "Soil removal plus labeled wet time addresses mold on hard tops when chronic moisture is fixed.",
    },
    M_CT,
    "Sink leaks and plant trays keep corners damp enough for mold on counters, backsplashes, and silicone joints.",
    "Disinfectant on cleaned surfaces reduces visible growth when humidity and leak paths are corrected.",
    ["Painting over moldy caulk.", "Ignoring dishwasher-side weeps."],
    "Visual growth should clear with dry-down; return means water is still reaching the site.",
    "Granite seams may need different dry strategy than quartz—map the wet source first.",
    ["EPA disinfectant use sites"],
  ),
  ct017a(
    "mildew stains",
    "biofilm",
    "alkaline",
    ["acidic"],
    {
      name: "Alkaline mildew cleaner tested for the countertop and adjacent grout",
      chemistry: "alkaline",
      surfaces: ["countertops", "tile"],
      avoids: ["acid same day without thorough rinse"],
      reason: "Surfactants lift mildew pigment from hard surfaces while improved ventilation slows return.",
    },
    M_CT,
    "Humid dishwashing and baths deposit mildew pigment on counter splashes and silicone joints.",
    "Alkaline cleaners remove surface staining while dry cycles show whether caulk must be replaced.",
    ["Short dwell leaving pigment.", "Soaking paper or wood countertops."],
    "Pigment should lighten when film has not penetrated silicone body.",
    "Pink stain through silicone usually needs new silicone, not only surface chemistry.",
    ["mildew cleaner labels"],
  ),
  ct017a(
    "etching",
    "damage",
    "neutral",
    ["acidic", "alkaline"],
    {
      name: "Neutral assessment wipe; stone or quartz professional for refinish if etched",
      chemistry: "neutral",
      surfaces: ["countertops"],
      avoids: ["stronger acid to blend sheen"],
      reason: "Etching is mineral or resin damage; neutral cleaning confirms removable haze versus permanent cloud.",
    },
    M_CT,
    "Lemon, vinegar, and wrong bowl cleaners spill onto marble or soften some resin tops locally.",
    "Neutral wipe distinguishes residue from permanent cloud; stone professionals hone or resurface when needed.",
    ["DIY acid etch repair experiments on marble.", "Assuming all clouding is hard water."],
    "Haze persisting after neutral clean means mechanical or professional correction.",
    "Some quartz chemical exposure reads like etch—verify with manufacturer before aggressive steps.",
    ["countertop damage triage notes"],
  ),
  ct017a(
    "oxidation",
    "damage",
    "neutral",
    ["acidic"],
    {
      name: "Neutral cleaner; UV-yellowed solid surface may need pro sand or replacement",
      chemistry: "neutral",
      surfaces: ["countertops"],
      avoids: ["bleach whitening experiments"],
      reason: "Polymer yellowing is not soil; neutral clean proves baseline before refinish or replace decisions.",
    },
    M_CT,
    "Sun through windows ages acrylic and some sealers unevenly across long counter runs.",
    "Cleaning removes grime; remaining yellow is material aging that needs refinish or new top.",
    ["Expecting peroxide to reverse all yellowing.", "Wax layers that trap heat and UV."],
    "If color mismatch persists when fully clean, plan material service not stronger chemistry.",
    "Window film often protects more than maintenance chemistry long term.",
    ["solid surface aging references"],
  ),
  ct017a(
    "corrosion",
    "damage",
    "neutral",
    ["acidic", "alkaline"],
    {
      name: "Neutral flush after stopping chemical exposure; replace pitted metal trim",
      chemistry: "neutral",
      surfaces: ["countertops"],
      avoids: ["continued drain cleaner splash"],
      reason: "Neutral rinsing halts active attack on metal edge trim and laminate until hardware is replaced.",
    },
    M_CT,
    "Drain opener and toilet cleaner splashes corrode sink clips and laminate edges in tight baths.",
    "Dilution and dry maintenance stop spread; pitted metal needs replacement not more acid.",
    ["Ignoring slow leak at soap dispenser bolt holes."],
    "Active flaking should stop after source control and thorough neutral flush.",
    "Map splash from adjacent toilet before blaming the counter material itself.",
    ["chemical splash damage notes"],
  ),
  ct017a(
    "tarnish",
    "residue",
    "neutral",
    ["acidic"],
    {
      name: "Neutral countertop cleaner or stone soap appropriate to material",
      chemistry: "neutral",
      surfaces: ["countertops", "sealed stone", "quartz"],
      avoids: ["oil soaps that build on quartz"],
      reason: "Smoky tarnish is often soap and oil film; neutral surfactants strip evenly across the field.",
    },
    M_CT,
    "Cleaner buildup and cooking films scatter light so counters look dull and blotchy in raking views.",
    "Even neutral cleaning restores uniform gloss on intact wear layers and sealers.",
    ["Spot-only polish creating halos.", "Vinegar habit on acid-sensitive stone inserts."],
    "Sheen should unify in cross-light when the issue was film not damage.",
    "Strip to neutral before assuming sealer failure everywhere.",
    ["daily countertop maintenance lines"],
  ),
  ct017a(
    "uneven finish",
    "residue",
    "neutral",
    ["acidic"],
    {
      name: "Neutral cleaner with even full-counter wipe; reseal stone only when fully clean and dry",
      chemistry: "neutral",
      surfaces: ["countertops", "sealed stone"],
      avoids: ["spot sealer blobs"],
      reason: "Uneven sheen is often differential residue or sealer; uniform neutral strip resets appearance.",
    },
    M_CT,
    "Partial wiping and uneven spray leave high-low gloss bands on long islands and perimeter runs.",
    "Full-field neutral clean matches refractive appearance before any reseal decision.",
    ["Resealing over damp stone.", "Cleaning only the coffee station half of a long run."],
    "Raking light across the full top should read even when residue caused variation.",
    "Photograph before; some patterns are stone movement or scratch wear not removable soil.",
    ["even maintenance technique notes"],
  ),
];

const GENERAL_HOUSEHOLD_017A: EvidenceRecord[] = [
  gh017a(
    "oil stains",
    "grease",
    "alkaline",
    ["acidic"],
    {
      name: "Mild alkaline cleaner for plastic utility bins and coated metals",
      chemistry: "alkaline",
      surfaces: ["general household surfaces", "garbage cans"],
      avoids: ["unknown painted metals without test"],
      reason: "Utility plastics and powder-coated bins collect oils that emulsify under mild alkaline surfactants when labeled.",
    },
    M_GH,
    "Trash cans and hampers hold hand oils and food drips that polymerize in warm utility zones and garages.",
    "Alkaline cleaner cuts grease on washable plastics and coated bins when dwell stays short and rinse is complete.",
    ["Using only disinfectant without degreasing first.", "Acid on galvanized without a hidden test."],
    "Oil sheen should reduce after dry-down.",
    "Outdoor rinse prevents sink grease transfer to food zones.",
    ["utility bin care notes"],
  ),
  gh017a(
    "food residue",
    "organic",
    "neutral",
    ["acidic"],
    {
      name: "Neutral all-purpose cleaner for bins and utility plastics",
      chemistry: "neutral",
      surfaces: ["garbage cans", "general household surfaces"],
      avoids: ["soaking labels you must keep legible"],
      reason: "Neutral surfactants lift dried food films without guessing every plastic additive in utility ware.",
    },
    M_GH,
    "Compost and kitchen scraps leave sugar films that attract insects inside cans and rolling totes.",
    "Neutral detergency releases organics so rinse water flushes residue out of the container.",
    ["Cold water only on dried jam bases.", "Cross-contaminating kitchen sponges into biohazard zones."],
    "Interior should feel smooth, not tacky, when fully dry.",
    "Liners reduce repeat adhesion on ribbed plastics.",
    ["waste container hygiene guides"],
  ),
  gh017a(
    "protein residue",
    "organic",
    "alkaline",
    ["acidic"],
    {
      name: "Cool alkaline or enzyme cleaner labeled for utility plastic",
      chemistry: "alkaline",
      surfaces: ["general household surfaces"],
      avoids: ["hot water on thin thermoformed bins"],
      reason: "Protein from pet waste and diapers bonds to plastic; cool alkaline or enzyme steps loosen it safely.",
    },
    M_GH,
    "Pet litter zones and diaper pails denature protein onto plastic walls that smell when interiors stay damp.",
    "Cool alkaline cleaning breaks protein films so mechanical scrub and rinse remove them completely.",
    ["Bleach without preclean.", "Sealed lids trapping moisture after rinsing."],
    "Odor and tack drop when protein is fully rinsed and the bin dries.",
    "Replace cracked bins where biofilm hides in crevices.",
    ["utility plastic cleaning references"],
  ),
  gh017a(
    "rust stains",
    "mineral",
    "acidic",
    ["alkaline"],
    {
      name: "Acidic rust spot treatment tested on hidden plastic or painted area",
      chemistry: "acidic",
      surfaces: ["garbage cans", "general household surfaces"],
      avoids: ["bleach mixes", "acid on unknown powder coat"],
      reason: "Targeted acid dissolves iron oxide from wet cans and garage track-in when substrate tolerates short contact.",
    },
    {
      tools: ["cotton swab", "timer"],
      dwell: "Spot",
      agitation: "Minimal",
      rinse: "Flood rinse",
      dry: "Inspect",
    },
    "Metal grates and fertilizer dust plate rust onto plastic cans and utility shelves in garages.",
    "Tested acidic gel lightens topical rust when colored plastic passes a hidden test.",
    ["Sheet-treating colored recycle bodies.", "Ignoring bolt rust bleeding from the inside out."],
    "Orange marks should step down without print damage in the test zone.",
    "Replace hardware when rust returns from interior corrosion.",
    ["rust spot labels for plastics"],
  ),
  gh017a(
    "tannin stains",
    "organic",
    "neutral",
    ["acidic"],
    {
      name: "Oxygen bleach tested on hidden plastic area",
      chemistry: "neutral",
      surfaces: ["general household surfaces"],
      avoids: ["chlorine with acid"],
      reason: "Controlled oxidation can lighten leaf tea and coffee films on some utility plastics when labeled.",
    },
    M_GH,
    "Yard waste and spilled drinks leave brown films on bins stored in garages and on patios.",
    "Controlled oxidizer may fade organic browns when the plastic manufacturer allows the chemistry.",
    ["Over-dwell fading colored recycle bins.", "Mixing incompatible oxidizers."],
    "Stain should lighten across passes or you accept dye absorption into aged plastic.",
    "Liners prevent repeat staining on next service cycle.",
    ["plastic oxidation stain notes"],
  ),
  gh017a(
    "mold growth",
    "biofilm",
    "alkaline",
    ["acidic"],
    {
      name: "EPA disinfectant after preclean on hard utility surfaces",
      chemistry: "alkaline",
      surfaces: ["garbage cans", "general household surfaces"],
      avoids: ["sealing over growth"],
      reason: "Preclean exposes mold to disinfectant on bins and shelving when labels match the plastic.",
    },
    M_GH,
    "Humid garages and drip lines from AC condensate sustain mold inside cans and on stored totes.",
    "Disinfectant at label wet time reduces growth when bins dry between uses and bags stop leaking.",
    ["Storing wet bags inside closed cans.", "Ignoring downspout splash on outdoor storage."],
    "Visual mold should clear; recurrence means moisture habit not weak chemistry.",
    "Drill weep holes only when the manufacturer approves.",
    ["EPA disinfectant non-food utility use"],
  ),
  gh017a(
    "mildew stains",
    "biofilm",
    "alkaline",
    ["acidic"],
    {
      name: "Alkaline mildew cleaner for plastic utility surfaces",
      chemistry: "alkaline",
      surfaces: ["general household surfaces"],
      avoids: ["acid without rinse between steps"],
      reason: "Surfactants lift mildew pigment from washable plastics with improved ventilation after cleaning.",
    },
    M_GH,
    "Closed damp cans and outdoor storage grow gray mildew pigment on ribbed plastic exteriors and lids.",
    "Alkaline cleaner plus dry storage lightens surface mildew staining when film is not scraped through.",
    ["Sealing lids without drying interiors first."],
    "Pigment fades when the film is superficial; scraped plastic may retain shadow.",
    "Store upside down after clean to finish drying completely.",
    ["outdoor bin maintenance"],
  ),
  gh017a(
    "etching",
    "damage",
    "neutral",
    ["acidic", "alkaline"],
    {
      name: "Neutral wipe for assessment; replace bin if plastic is frosted through",
      chemistry: "neutral",
      surfaces: ["general household surfaces"],
      avoids: ["stronger acid to clear frost"],
      reason: "Chemical frost on plastic is damage; neutral clean confirms non-removable haze versus residue.",
    },
    M_GH,
    "Pool chemicals and wrong cleaners cloud clear plastic totes and lids used in garages and sheds.",
    "Neutral cleaning distinguishes residue from etched plastic that needs retirement or relabeling.",
    ["Scrubbing frosted plastic until it turns opaque."],
    "Haze remains after neutral wipe means replace or downgrade bin duty.",
    "Segregate chemical storage away from household plastics.",
    ["plastic chemical damage notes"],
  ),
  gh017a(
    "oxidation",
    "damage",
    "neutral",
    ["acidic"],
    {
      name: "Neutral cleaner; UV-brittle plastic needs replacement not whitening chemistry",
      chemistry: "neutral",
      surfaces: ["general household surfaces"],
      avoids: ["bleach on colored recycle bodies"],
      reason: "Chalking and yellowing are polymer aging; cleaning removes grime atop chalk before replace timing.",
    },
    M_GH,
    "Outdoor bins yellow and craze from UV and winter cycles even when owners wash regularly.",
    "Neutral wash removes surface soil; remaining fade signals material replacement timing.",
    ["Expecting wax to restore UV chalk permanently."],
    "If chalk returns immediately after wash, the plastic is structurally exhausted.",
    "Store in shade when possible to extend service life.",
    ["UV plastic aging context"],
  ),
  gh017a(
    "corrosion",
    "damage",
    "neutral",
    ["acidic", "alkaline"],
    {
      name: "Neutral flush; replace corroded metal parts on rolling cans",
      chemistry: "neutral",
      surfaces: ["general household surfaces"],
      avoids: ["road salt exposure continuing on hardware"],
      reason: "Road salt and fertilizer corrode axles and hinges; neutral rinse slows spread until parts swap.",
    },
    {
      tools: ["hose", "wrench"],
      dwell: "N/A",
      agitation: "Rinse wheels and hinges",
      rinse: "Low pressure thorough",
      dry: "Lubricate per manufacturer",
    },
    "Garage cans get chloride spray from cars and deicers that pit metal hardware and stain plastic.",
    "Rinsing and drying hardware reduces ongoing corrosion until replacement parts install.",
    ["Ignoring squeal that signals bearing rust."],
    "Active rust dust should stop after rinse and dry habit improvements.",
    "Use stainless or coated hardware on replacements when available.",
    ["utility cart corrosion maintenance"],
  ),
  gh017a(
    "tarnish",
    "residue",
    "neutral",
    ["acidic"],
    {
      name: "Neutral cleaner for smoky film on plastic and painted utility surfaces",
      chemistry: "neutral",
      surfaces: ["garbage cans", "general household surfaces"],
      avoids: ["solvent that crazes polycarbonate"],
      reason: "Smoky tarnish is usually soil film; neutral surfactants restore even appearance on intact coatings.",
    },
    M_GH,
    "Dust, grease, and pollen layer into a dull film on cans stored near driveways and curbs.",
    "Neutral surfactant and rinse restore color uniformity on intact plastic not UV-faded through.",
    ["Using furniture polish that attracts more dust on ribbed bodies."],
    "Color should pop again when the issue was film not polymer fade.",
    "Seasonal deep clean beats heavy buildup cycles.",
    ["utility surface film removal"],
  ),
];

export const BATCH_017A_EVIDENCE: EvidenceRecord[] = [
  ...TRIPLE_017A,
  ...COUNTERTOP_017A,
  ...GENERAL_HOUSEHOLD_017A,
];
